"""Artifact construction, persistence, and reload validation for the specialist."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import Any, Iterable

from .generator import (
    RUNG_SIZES,
    build_ladder,
    generate_canonical,
    generate_holdout,
    generate_qa,
)
from .ontology import ontology_payload
from .requirements import compile_requirements
from .schemas import tool_schemas
from .validator import coverage_matrix, validate_dataset


def _json_bytes(value: Any, *, pretty: bool = True) -> bytes:
    if pretty:
        text = json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    else:
        text = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return text.encode("utf-8")


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(_json_bytes(value))


def _write_jsonl(path: Path, rows: Iterable[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(
                json.dumps(row, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
                + "\n"
            )


def _read_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL at {path}:{line_number}: {exc}") from exc
    return rows


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _dataset_hash(rows: list[dict]) -> str:
    payload = [
        {
            "id": row["id"],
            "query": row["query"],
            "answers": row["answers"],
            "requirement_ids": row["requirement_ids"],
        }
        for row in rows
    ]
    return hashlib.sha256(_json_bytes(payload, pretty=False)).hexdigest()


def _coverage_markdown(coverage: dict[str, Any]) -> str:
    headers = [str(size) for size in RUNG_SIZES]
    lines = [
        "# Essencebound Dataset Coverage",
        "",
        "| Category | " + " | ".join(headers) + " |",
        "|---|" + "---:|" * len(headers),
    ]
    for category, counts in coverage["categories"].items():
        lines.append(
            f"| {category} | " + " | ".join(str(counts.get(size, 0)) for size in headers) + " |"
        )
    lines.extend(["", "All counts come from generated rung files.", ""])
    return "\n".join(lines)


def _readme() -> str:
    return """# NEEDLE-EB-WORLD-ARCHITECT

This directory is generated by `foundry.essencebound_world` from the approved Essencebound master specification.

The enriched JSONL rows retain audit metadata and Needle 2's native `query` / `reasoning` / `answers` / `tools` fields. Tool arguments use compact bounded codes defined in `source/ontology.json`; MUSE renders them deterministically.

## Rebuild and validate

```powershell
uv sync --extra dev --extra foundry
uv run --extra foundry python -m foundry.essencebound_world.cli build-data --source <master-prompt> --output Training\\Needle\\EB_World_Architect
uv run --extra foundry python -m foundry.essencebound_world.cli validate --root Training\\Needle\\EB_World_Architect
```

The `foundry` extra pins the public Needle 2 package used by validation and inference. Training additionally requires the pinned source checkpoint under `third_party/needle`; preflight fails closed when those external artifacts or the verified float32-LoRA patch are absent.

Training and promotion are fail-closed. A generated dataset is not evidence that a model trained or passed evaluation; inspect `reports/gate_results.json` and the measured run artifacts.
"""


def _artifact_manifest(root: Path, dataset_hash: str, source_hash: str) -> dict[str, Any]:
    files = {
        path.relative_to(root).as_posix(): _sha256(path)
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.name != "manifest.json"
    }
    return {
        "specialist": "needle-eb-world-architect",
        "dataset_hash": dataset_hash,
        "source_hash": source_hash,
        "files": files,
    }


def _build_into(source: Path, root: Path) -> dict[str, Any]:
    source_text = source.read_text(encoding="utf-8")
    source_hash = hashlib.sha256(source_text.encode("utf-8")).hexdigest()
    requirements = compile_requirements(source_text)
    ontology = ontology_payload()
    schemas = tool_schemas()
    canonical = generate_canonical(requirements, 4000)
    ladders = build_ladder(canonical)
    qa = generate_qa(requirements, 4000)
    holdout = generate_holdout(requirements, 400)
    validation = validate_dataset(canonical, ladders, qa, holdout)
    if not validation["passed"]:
        raise ValueError(
            "generated dataset failed validation: "
            + json.dumps(validation["errors"][:10], ensure_ascii=False)
        )

    source_dir = root / "source"
    source_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, source_dir / "master_prompt.md")
    _write_json(source_dir / "requirements.json", requirements)
    _write_json(source_dir / "ontology.json", ontology)
    _write_json(source_dir / "tool_schemas.json", schemas)
    (source_dir / "master_prompt.sha256").write_text(source_hash + "\n", encoding="utf-8")

    for size, splits in ladders.items():
        rung = root / f"rung_{size:04d}"
        for split_name, rows in splits.items():
            _write_jsonl(rung / f"{split_name}.jsonl", rows)
    qa_dir = root / "qa"
    for size in RUNG_SIZES:
        _write_jsonl(qa_dir / f"qa_{size:04d}.jsonl", qa[:size])
    _write_jsonl(root / "holdout" / "needle_eb_world_holdout.jsonl", holdout)

    coverage = coverage_matrix(ladders)
    reports = root / "reports"
    _write_json(reports / "coverage.json", coverage)
    (reports / "coverage.md").write_text(
        _coverage_markdown(coverage), encoding="utf-8", newline="\n"
    )
    stats = {
        "requirements": len(requirements),
        "canonical_examples": len(canonical),
        "qa_examples": len(qa),
        "holdout_examples": len(holdout),
        "rungs": validation["rungs"],
        "duplicate_rate": validation["duplicate_rate"],
        "failure_fraction": validation["pools"]["canonical"]["counts"]["failure_rows"]
        / len(canonical),
        "adversarial_fraction": validation["pools"]["canonical"]["counts"]["adversarial_rows"]
        / len(canonical),
        "max_training_tokens": {
            pool: report["counts"]["max_training_tokens"]
            for pool, report in validation["pools"].items()
        },
    }
    _write_json(reports / "dataset_stats.json", stats)
    _write_json(reports / "dataset_validation.json", validation)
    (reports / "deduplication.md").write_text(
        "# Deduplication Report\n\n"
        f"Exact normalized duplicate rate: {validation['duplicate_rate']:.6f}\n\n"
        "Canonical, QA, and holdout query and semantic-family intersections: 0.\n",
        encoding="utf-8",
        newline="\n",
    )
    _write_json(
        reports / "gate_results.json",
        {"status": "NOT_RUN", "reason": "No measured training or evaluation run exists.", "rungs": {}},
    )
    (root / "README.md").write_text(_readme(), encoding="utf-8", newline="\n")

    dataset_hash = _dataset_hash(canonical)
    manifest = _artifact_manifest(root, dataset_hash, source_hash)
    _write_json(root / "manifest.json", manifest)
    return {
        "requirements": len(requirements),
        "dataset_hash": dataset_hash,
        "source_hash": source_hash,
        "validation": validation,
        "stats": stats,
        "manifest": manifest,
    }


def build_data(source: Path | str, output: Path | str) -> dict[str, Any]:
    """Build in a sibling staging directory and publish only after validation."""
    source = Path(source).resolve()
    output = Path(output).resolve()
    if not source.is_file():
        raise FileNotFoundError(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}.building-", dir=output.parent))
    backup: Path | None = None
    try:
        result = _build_into(source, staging)
        if output.exists():
            backup = Path(tempfile.mkdtemp(prefix=f".{output.name}.previous-", dir=output.parent))
            backup.rmdir()
            os.replace(output, backup)
        os.replace(staging, output)
        if backup is not None:
            shutil.rmtree(backup)
        return result
    except Exception:
        if staging.exists():
            shutil.rmtree(staging)
        if backup is not None and backup.exists() and not output.exists():
            os.replace(backup, output)
        raise


def validate_root(root: Path | str) -> dict[str, Any]:
    """Reload generated files, re-run validation, and verify every manifest hash."""
    root = Path(root).resolve()
    canonical_rows = []
    ladders: dict[int, dict[str, list[dict]]] = {}
    for size in RUNG_SIZES:
        rung = root / f"rung_{size:04d}"
        splits = {
            name: _read_jsonl(rung / f"{name}.jsonl")
            for name in ("train", "validation", "test")
        }
        ladders[size] = splits
        if size == 4000:
            canonical_rows = sorted(
                [row for values in splits.values() for row in values], key=lambda row: row["id"]
            )
    qa = _read_jsonl(root / "qa" / "qa_4000.jsonl")
    holdout = _read_jsonl(root / "holdout" / "needle_eb_world_holdout.jsonl")
    report = validate_dataset(canonical_rows, ladders, qa, holdout)
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    hash_errors = []
    for relative, expected in manifest.get("files", {}).items():
        path = root / relative
        actual = _sha256(path) if path.is_file() else None
        if actual != expected:
            hash_errors.append(
                {"code": "artifact_hash_mismatch", "file": relative, "expected": expected, "actual": actual}
            )
    if hash_errors:
        report["errors"].extend(hash_errors)
        report["passed"] = False
    report["manifest_hashes_passed"] = not hash_errors
    return report


def refresh_manifest(root: Path | str) -> dict[str, Any]:
    """Re-hash a built tree after measured run artifacts are appended."""
    root = Path(root).resolve()
    current = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    manifest = _artifact_manifest(root, current["dataset_hash"], current["source_hash"])
    _write_json(root / "manifest.json", manifest)
    return manifest
