"""Supabase integration adapter.

Hermes treats Supabase as a *schema and migrations* surface, not as a
data-mutation surface. The adapter helps the agent:

- detect whether the ``supabase`` CLI is installed,
- propose a schema in a structured form,
- generate a migration file under ``supabase/migrations/<ts>_<slug>.sql``,
- emit the local-first ``supabase db reset`` / ``supabase db push``
  command sequence so a human can apply it,

…but it never reaches into a production project on its own. Any
``supabase db push`` against a remote project requires an explicit
operator approval gate; the adapter just prints the command.

The Supabase MCP server (``mcp__55d18...``) is more capable, but it
operates on whatever project is configured server-side. This adapter is
deliberately the *local* path: SQL files committed to the repo, applied
through the CLI under operator control.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Sequence

__all__ = [
    "Detection",
    "ColumnSpec",
    "TableSpec",
    "SupabasePlan",
    "SupabaseExecutionResult",
    "detect",
    "plan",
    "render_migration_sql",
    "explain",
    "execute",
]


_SLUG = re.compile(r"[^a-z0-9]+")


def _slug(value: str, *, fallback: str = "migration") -> str:
    s = _SLUG.sub("_", (value or "").lower()).strip("_")
    return s or fallback


@dataclass(frozen=True)
class Detection:
    cli_present: bool
    cli_path: Optional[str]
    project_root: Optional[Path]
    has_supabase_dir: bool
    notes: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class ColumnSpec:
    name: str
    type: str
    nullable: bool = True
    default: Optional[str] = None
    primary_key: bool = False
    unique: bool = False
    references: Optional[str] = None  # "other_table(id)" form

    def render(self) -> str:
        parts = [f"  {self.name}", self.type]
        if self.primary_key:
            parts.append("primary key")
        if self.unique and not self.primary_key:
            parts.append("unique")
        if not self.nullable and not self.primary_key:
            parts.append("not null")
        if self.default is not None:
            parts.append(f"default {self.default}")
        if self.references:
            parts.append(f"references {self.references}")
        return " ".join(parts)


@dataclass(frozen=True)
class TableSpec:
    name: str
    columns: Sequence[ColumnSpec]
    schema: str = "public"
    enable_rls: bool = True
    comment: Optional[str] = None


@dataclass(frozen=True)
class SupabasePlan:
    migration_name: str
    timestamp: str
    migration_path: Path
    tables: list[TableSpec]
    sql: str
    local_commands: list[list[str]]
    remote_commands: list[list[str]]
    cli_present: bool
    secrets_policy: list[str]
    rollback_notes: list[str]
    validation_steps: list[str]
    approval_required: bool = True
    dry_run: bool = True


@dataclass(frozen=True)
class SupabaseExecutionResult:
    executed: bool
    wrote_migration: bool
    migration_path: Optional[Path]
    errors: list[str]


def detect(project_root: Optional[Path] = None) -> Detection:
    """Probe for the ``supabase`` CLI and a local ``supabase/`` directory."""
    cli_path = shutil.which("supabase")
    root = (project_root or Path.cwd()).resolve()
    sb_dir = root / "supabase"
    has_dir = sb_dir.is_dir()
    notes: list[str] = []
    if cli_path is None:
        notes.append(
            "`supabase` CLI not on PATH — install from https://supabase.com/docs/guides/local-development."
        )
    if not has_dir:
        notes.append(
            "No `supabase/` directory at project root — run `supabase init` first to create one."
        )
    return Detection(
        cli_present=cli_path is not None,
        cli_path=cli_path,
        project_root=root,
        has_supabase_dir=has_dir,
        notes=notes,
    )


def render_migration_sql(
    tables: Sequence[TableSpec],
    *,
    header: Optional[str] = None,
) -> str:
    """Render a CREATE TABLE migration for ``tables``.

    Always idempotent (``create table if not exists``) and always
    enables RLS by default — Supabase's own guidance is that tables
    without RLS are a security hazard.
    """
    out: list[str] = []
    if header:
        for line in header.splitlines():
            out.append(f"-- {line}")
        out.append("")
    out.append("-- Generated by muse_cli.integrations.supabase")
    out.append("-- Review locally with `supabase db reset` before applying remotely.")
    out.append("")
    for t in tables:
        full = f"{t.schema}.{t.name}"
        if t.comment:
            out.append(f"-- {t.comment}")
        out.append(f"create table if not exists {full} (")
        cols = [c.render() for c in t.columns]
        out.append(",\n".join(cols))
        out.append(");")
        if t.enable_rls:
            out.append(f"alter table {full} enable row level security;")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def plan(
    *,
    migration_name: str,
    tables: Sequence[TableSpec],
    project_root: Optional[Path] = None,
    timestamp: Optional[str] = None,
    header: Optional[str] = None,
) -> SupabasePlan:
    """Build a migration plan without touching the filesystem.

    The returned :class:`SupabasePlan` carries the SQL, the eventual
    file path under ``supabase/migrations/``, and the command sequences
    a human would run locally and (with approval) remotely.
    """
    if not tables:
        raise ValueError("supabase plan requires at least one table")
    root = (project_root or Path.cwd()).resolve()
    ts = timestamp or datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    slug = _slug(migration_name)
    filename = f"{ts}_{slug}.sql"
    migration_path = root / "supabase" / "migrations" / filename

    sql = render_migration_sql(tables, header=header or migration_name)

    local_cmds = [
        ["supabase", "start"],
        ["supabase", "db", "reset"],
        ["supabase", "db", "diff", "--use-migra"],
    ]
    remote_cmds = [
        ["supabase", "link", "--project-ref", "<project-ref>"],
        ["supabase", "db", "push"],
    ]
    secrets_policy = [
        "Service-role keys live in ~/.hermes/.env or your shell — never commit them.",
        "Migrations may reference roles/policies but must not embed JWT secrets, API keys, or passwords.",
        "Seed data with PII goes in a `.gitignored` seed file, not in the migration.",
    ]
    rollback_notes = [
        "Delete the freshly written migration file before re-running `supabase db reset` to drop the change locally.",
        "For remote rollback, write a follow-up migration that issues the inverse DDL (drop table / drop column) — never edit a migration that has already been pushed.",
        "If `supabase db push` failed mid-way, capture the error, then re-link and retry only after the underlying issue is fixed.",
    ]
    validation_steps = [
        "Run `supabase db reset` locally and confirm the migration applies cleanly on an empty DB.",
        "Run the project's test suite against the local Supabase instance.",
        "Run `supabase db diff` and confirm it reports no drift between the migration and the local schema.",
        "Manually inspect RLS policies — every new table should have either a policy or an intentional `bypass` reason.",
    ]

    return SupabasePlan(
        migration_name=slug,
        timestamp=ts,
        migration_path=migration_path,
        tables=list(tables),
        sql=sql,
        local_commands=local_cmds,
        remote_commands=remote_cmds,
        cli_present=detect(root).cli_present,
        secrets_policy=secrets_policy,
        rollback_notes=rollback_notes,
        validation_steps=validation_steps,
        approval_required=True,
        dry_run=True,
    )


def explain(p: SupabasePlan) -> str:
    """Render ``p`` as plain-English markdown."""
    lines: list[str] = []
    lines.append(f"### Supabase migration plan — `{p.migration_name}`")
    lines.append("")
    lines.append(
        f"I want to write a new migration file to "
        f"`{p.migration_path.relative_to(p.migration_path.parents[2]) if len(p.migration_path.parents) >= 3 else p.migration_path}` "
        f"that creates {len(p.tables)} table(s): "
        + ", ".join(f"`{t.schema}.{t.name}`" for t in p.tables)
        + "."
    )
    lines.append("")
    lines.append(f"**Approval required:** {'yes' if p.approval_required else 'no'}")
    lines.append(f"**`supabase` CLI present:** {'yes' if p.cli_present else 'no'}")
    lines.append("")
    lines.append("**Local-first command sequence (safe to run):**")
    lines.append("```bash")
    for cmd in p.local_commands:
        lines.append(" ".join(cmd))
    lines.append("```")
    lines.append("")
    lines.append("**Remote command sequence (requires explicit approval):**")
    lines.append("```bash")
    for cmd in p.remote_commands:
        lines.append(" ".join(cmd))
    lines.append("```")
    lines.append("")
    lines.append("**Secrets policy:**")
    for note in p.secrets_policy:
        lines.append(f"- {note}")
    lines.append("")
    lines.append("**Rollback:**")
    for note in p.rollback_notes:
        lines.append(f"- {note}")
    lines.append("")
    lines.append("**Validation:**")
    for step in p.validation_steps:
        lines.append(f"- {step}")
    return "\n".join(lines) + "\n"


def execute(
    p: SupabasePlan,
    *,
    approve: bool = False,
) -> SupabaseExecutionResult:
    """Write the migration file to disk if approved.

    Never runs ``supabase db push`` or any other CLI command. The
    operator is expected to run the local/remote command sequences from
    ``explain()`` themselves — this adapter only materializes the SQL.
    """
    if not approve:
        return SupabaseExecutionResult(
            executed=False,
            wrote_migration=False,
            migration_path=None,
            errors=["approve=False — refused to write migration"],
        )
    errors: list[str] = []
    try:
        p.migration_path.parent.mkdir(parents=True, exist_ok=True)
        p.migration_path.write_text(p.sql, encoding="utf-8")
    except OSError as exc:
        errors.append(f"failed to write migration: {exc}")
        return SupabaseExecutionResult(
            executed=False,
            wrote_migration=False,
            migration_path=None,
            errors=errors,
        )
    return SupabaseExecutionResult(
        executed=True,
        wrote_migration=True,
        migration_path=p.migration_path,
        errors=errors,
    )
