/**
 * Built-in route registration.
 *
 * This module is imported once for its side effect (from main.tsx) and seeds
 * the append-only registry with the routes this scaffold ships — currently just
 * Home. Feature grains register their own routes from their own modules; they
 * do NOT edit this file (that keeps registration conflict-free across parallel
 * grains). If a grain wants its registration to load eagerly at startup, it can
 * add a single side-effect import here, but the registry itself is the seam.
 */
import { createElement } from "react";
import { registerRoute } from "./routes";
import { Home } from "./views/Home";

registerRoute({
  id: "home",
  label: "Legacy Home",
  order: 100,
  render: () => createElement(Home),
});
