#!/usr/bin/env node
// @muse/design-system — token generator.
//
// PURE Node, zero dependencies. Reads ../tokens.json (the canonical source)
// and emits platform artifacts into ../dist:
//   - tokens.css  : CSS custom properties for the web cockpit.
//   - Tokens.kt   : a Kotlin `object museTokens` for the Compose Android app.
//
// Both targets are GENERATED — never hand-edit dist/. Edit tokens.json and
// re-run `npm run build`. This is what keeps web + Android pixel-identical.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DIST = join(ROOT, "dist");

const tokens = JSON.parse(readFileSync(join(ROOT, "tokens.json"), "utf8"));

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/** "#aabbcc" -> "0xFFAABBCC" (Compose Color literal). */
function hexToComposeLong(hex) {
  const h = hex.replace("#", "").toUpperCase();
  if (h.length !== 6) {
    throw new Error(`generate: expected 6-digit hex, got "${hex}"`);
  }
  return `0xFF${h}`;
}

/** camelCase a token key like "signal-dim" -> "signalDim". */
function camel(key) {
  return key.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

const colorEntries = Object.entries(tokens.color);
const radiusEntries = Object.entries(tokens.radius).filter(
  ([k]) => k !== "comment",
);
const spacingEntries = Object.entries(tokens.spacing.scale);
const durationEntries = Object.entries(tokens.motion.duration);
const easingEntries = Object.entries(tokens.motion.easing);
const typeEntries = Object.entries(tokens.type.scale);

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

function buildCss() {
  const L = [];
  L.push("/* GENERATED by @muse/design-system — do not edit by hand.");
  L.push(" * Source of truth: design-system/tokens.json. Run `npm run build`.");
  L.push(" * muse 'Singularity' tokens — white core in the void, one spectral ring.");
  L.push(" */");
  L.push(":root {");

  L.push("  /* color */");
  for (const [k, v] of colorEntries) {
    const comment = v.comment ? ` /* ${v.comment} */` : "";
    L.push(`  --${k}: ${v.value};${comment}`);
  }

  L.push("");
  L.push("  /* gradient */");
  L.push(`  --ring-grad: ${tokens.gradient.ring.value};`);

  L.push("");
  L.push("  /* spacing — 4/8 grid */");
  for (const [k, v] of spacingEntries) {
    L.push(`  --space-${k}: ${v}px;`);
  }

  L.push("");
  L.push("  /* radius */");
  for (const [k, v] of radiusEntries) {
    L.push(`  --radius-${k}: ${v}px;`);
  }
  // back-compat alias matching the cockpit's existing --radius (md = 12px).
  L.push(`  --radius: ${tokens.radius.md}px;`);

  L.push("");
  L.push("  /* type — font stacks */");
  L.push(`  --font-sans: ${tokens.type.font.sans};`);
  L.push(`  --font-mono: ${tokens.type.font.mono};`);
  // back-compat aliases matching the cockpit's existing --sans / --mono.
  L.push(`  --sans: ${tokens.type.font.sans};`);
  L.push(`  --mono: ${tokens.type.font.mono};`);

  L.push("");
  L.push("  /* type — scale (size / weight / letter-spacing / line-height) */");
  for (const [k, v] of typeEntries) {
    L.push(`  --type-${k}-size: ${v.size}px;`);
    L.push(`  --type-${k}-weight: ${v.weight};`);
    L.push(`  --type-${k}-tracking: ${v.letterSpacing}px;`);
    L.push(`  --type-${k}-line: ${v.lineHeight}px;`);
  }

  L.push("");
  L.push("  /* elevation — tonal overlays, NOT drop shadows */");
  for (const [k, v] of Object.entries(tokens.elevation.level)) {
    L.push(`  --elevation-${k}: ${v.value};`);
  }

  L.push("");
  L.push("  /* motion — durations */");
  for (const [k, v] of durationEntries) {
    L.push(`  --duration-${k}: ${v}ms;`);
  }
  L.push("");
  L.push("  /* motion — easing (Material 3) */");
  for (const [k, v] of easingEntries) {
    L.push(`  --easing-${k}: ${v};`);
  }

  L.push("");
  L.push("  /* glyph geometry (ratios relative to viewBox) */");
  L.push(`  --glyph-core-ratio: ${tokens.glyph.coreRadiusRatio};`);
  L.push(`  --glyph-ring-ratio: ${tokens.glyph.ringRadiusRatio};`);
  L.push(`  --glyph-ring-stroke-ratio: ${tokens.glyph.ringStrokeRatio};`);
  L.push(`  --glyph-dasharray: ${tokens.glyph.dasharray.join(" ")};`);
  L.push(`  --glyph-rotate: ${tokens.glyph.rotate}deg;`);

  L.push("}");
  L.push("");
  return L.join("\n");
}

// ---------------------------------------------------------------------------
// Kotlin
// ---------------------------------------------------------------------------

function buildKotlin() {
  const L = [];
  L.push("// GENERATED by @muse/design-system — do not edit by hand.");
  L.push("// Source of truth: design-system/tokens.json. Run `npm run build`.");
  L.push("// muse 'Singularity' tokens — white core in the void, one spectral ring.");
  L.push("//");
  L.push("// Consume from Compose, e.g. `Surface(color = museTokens.Color.void)`.");
  L.push("@file:Suppress(\"unused\", \"ConstPropertyName\", \"MemberVisibilityCanBePrivate\")");
  L.push("");
  L.push("package muse.designsystem");
  L.push("");
  L.push("import androidx.compose.ui.graphics.Color");
  L.push("import androidx.compose.ui.text.font.FontWeight");
  L.push("import androidx.compose.ui.unit.dp");
  L.push("import androidx.compose.ui.unit.sp");
  L.push("");
  L.push("object museTokens {");

  // Color
  L.push("    object Color {");
  for (const [k, v] of colorEntries) {
    const name = camel(k);
    L.push(`        val ${name} = androidx.compose.ui.graphics.Color(${hexToComposeLong(v.value)})`);
  }
  L.push("    }");
  L.push("");

  // Ring gradient stops (Compose has no CSS gradient literal; expose the stops).
  L.push("    /** Spectral ring gradient stops (cyan -> violet). */");
  L.push("    val ringGradientStops = listOf(");
  for (const stop of tokens.gradient.ring.stops) {
    L.push(`        androidx.compose.ui.graphics.Color(${hexToComposeLong(stop)}),`);
  }
  L.push("    )");
  L.push("");

  // Spacing
  L.push("    object Spacing {");
  for (const [k, v] of spacingEntries) {
    L.push(`        val s${k} = ${v}.dp`);
  }
  L.push("    }");
  L.push("");

  // Radius
  L.push("    object Radius {");
  for (const [k, v] of radiusEntries) {
    L.push(`        val ${k} = ${v}.dp`);
  }
  L.push("    }");
  L.push("");

  // Type
  L.push("    object Font {");
  L.push(`        const val sans = ${JSON.stringify(tokens.type.font.sans)}`);
  L.push(`        const val mono = ${JSON.stringify(tokens.type.font.mono)}`);
  L.push("    }");
  L.push("");
  L.push("    /** Type scale: size + weight + letter-spacing + line-height. */");
  L.push("    data class TypeStyle(");
  L.push("        val size: androidx.compose.ui.unit.TextUnit,");
  L.push("        val weight: FontWeight,");
  L.push("        val letterSpacing: androidx.compose.ui.unit.TextUnit,");
  L.push("        val lineHeight: androidx.compose.ui.unit.TextUnit,");
  L.push("    )");
  L.push("    object Type {");
  for (const [k, v] of typeEntries) {
    L.push(
      `        val ${camel(k)} = TypeStyle(${v.size}.sp, FontWeight(${v.weight}), ${v.letterSpacing}.sp, ${v.lineHeight}.sp)`,
    );
  }
  L.push("    }");
  L.push("");

  // Elevation (tonal overlays -> Color)
  L.push("    /** Elevation as tonal surface colors (NOT drop shadows). */");
  L.push("    object Elevation {");
  for (const [k, v] of Object.entries(tokens.elevation.level)) {
    L.push(`        val ${camel(k)} = androidx.compose.ui.graphics.Color(${hexToComposeLong(v.value)})`);
  }
  L.push("    }");
  L.push("");

  // Motion
  L.push("    object Motion {");
  L.push("        object Duration {");
  for (const [k, v] of durationEntries) {
    L.push(`            const val ${k} = ${v}`); // milliseconds
  }
  L.push("        }");
  L.push("        /** Material 3 easing curves as cubic-bezier control points (x1, y1, x2, y2). */");
  L.push("        object Easing {");
  for (const [k, v] of easingEntries) {
    const nums = v.replace("cubic-bezier(", "").replace(")", "").split(",").map((s) => s.trim());
    L.push(`            val ${k} = floatArrayOf(${nums.map((n) => `${n}f`).join(", ")})`);
  }
  L.push("        }");
  L.push("    }");
  L.push("");

  // Glyph
  L.push("    object Glyph {");
  L.push(`        const val coreRadiusRatio = ${tokens.glyph.coreRadiusRatio}f`);
  L.push(`        const val ringRadiusRatio = ${tokens.glyph.ringRadiusRatio}f`);
  L.push(`        const val ringStrokeRatio = ${tokens.glyph.ringStrokeRatio}f`);
  L.push(`        val dasharray = floatArrayOf(${tokens.glyph.dasharray.map((n) => `${n}f`).join(", ")})`);
  L.push(`        const val rotate = ${tokens.glyph.rotate}f`);
  L.push("    }");

  L.push("}");
  L.push("");
  return L.join("\n");
}

// ---------------------------------------------------------------------------
// emit
// ---------------------------------------------------------------------------

mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, "tokens.css"), buildCss(), "utf8");
writeFileSync(join(DIST, "Tokens.kt"), buildKotlin(), "utf8");

console.log("generated dist/tokens.css and dist/Tokens.kt from tokens.json");
