"""UE5.7 C++ scaffolding adapter — emits a real compiling Unreal project.

This adapter replaces the minimal `.uproject`-only scaffold with a full UE 5.7
C++ project that compiles against the locally installed engine via
`UnrealBuildTool` / `Build.bat`. It mirrors the structure of the shipped
`TP_Blank` template (which was read off this machine's install) and extends it
with gameplay classes (GameMode, Character, PlayerController, HUD) derived from
the GameBrief.

Files written (engine="ue5", module name derived from title slug):
    <Proj>/<Proj>.uproject                 — EngineAssociation="5.7", module + plugin list
    <Proj>/Source/<Mod>/<Mod>.Build.cs      — ModuleRules, V6 build settings
    <Proj>/Source/<Mod>Target.Target.cs      — Game target, Unreal5_7 include order
    <Proj>/Source/<Mod>EditorTarget.Target.cs — Editor target
    <Proj>/Source/<Mod>/<Mod>.h + .cpp      — IMPLEMENT_PRIMARY_GAME_MODULE
    <Proj>/Source/<Mod>/<Mod>GameMode.h/.cpp
    <Proj>/Source/<Mod>/<Mod>Character.h/.cpp
    <Proj>/Source/<Mod>/<Mod>PlayerController.h/.cpp
    <Proj>/Source/<Mod>/<Mod>HUD.h/.cpp
    <Proj>/Config/DefaultEngine.ini          — DX12, 8K scalability, audio
    <Proj>/Config/DefaultGame.ini
    <Proj>/Config/DefaultInput.ini           — Enhanced Input
    <Proj>/Content/                          — asset target dir
    <Proj>/README.md

All C++ is valid against UE 5.7 API (Core, CoreUObject, Engine, InputCore,
EnhancedInput, SlateUI). The project builds with:
    "<UE5>/Engine/Build/BatchFiles/Build.bat" <Mod>Editor Win64 Development -Project="<Proj>/<Proj>.uproject"
"""
from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path
from typing import List, Tuple

from agent.studio.adapters.base import Adapter, default_registry
from agent.studio.types import Provider


UE5_ENGINE_ROOT = os.environ.get(
    "UE5_ENGINE_ROOT", r"C:\Program Files\Epic Games\UE_5.7"
)
UE5_ENGINE_ASSOCIATION = "5.7"
UE5_INCLUDE_ORDER = "EngineIncludeOrderVersion.Unreal5_7"
UE5_BUILD_SETTINGS = "BuildSettingsVersion.V6"


def _slug(title: str) -> str:
    """UE module name: PascalCase, alphanumeric, no leading digit."""
    s = "".join(c if c.isalnum() else " " for c in title)
    parts = [p for p in s.split() if p]
    mod = "".join(p[:1].upper() + p[1:] for p in parts) if parts else "Game"
    mod = re.sub(r"[^A-Za-z0-9]", "", mod)
    if mod and mod[0].isdigit():
        mod = "G" + mod
    return mod or "Game"


def _upid(title: str) -> str:
    """Lowercase project folder name."""
    return _slug(title)


# ── C++ source templates (UE 5.7 API) ──────────────────────────────────

def _build_cs(mod: str) -> str:
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
using UnrealBuildTool;

public class {mod} : ModuleRules
{{
    public {mod}(ReadOnlyTargetRules Target) : base(Target)
    {{
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        PublicDependencyModuleNames.AddRange(new string[] {{
            "Core", "CoreUObject", "Engine", "InputCore", "EnhancedInput"
        }});

        PrivateDependencyModuleNames.AddRange(new string[] {{
            "Slate", "SlateCore", "UMG"
        }});

        // Uncomment for online features
        // PrivateDependencyModuleNames.Add("OnlineSubsystem");
    }}
}}
"""


def _game_target(mod: str) -> str:
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
using UnrealBuildTool;
using System.Collections.Generic;

public class {mod}Target : TargetRules
{{
    public {mod}Target(TargetInfo Target) : base(Target)
    {{
        Type = TargetType.Game;
        DefaultBuildSettings = {UE5_BUILD_SETTINGS};
        IncludeOrderVersion = {UE5_INCLUDE_ORDER};
        ExtraModuleNames.Add("{mod}");
    }}
}}
"""


def _editor_target(mod: str) -> str:
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
using UnrealBuildTool;
using System.Collections.Generic;

public class {mod}EditorTarget : TargetRules
{{
    public {mod}EditorTarget(TargetInfo Target) : base(Target)
    {{
        Type = TargetType.Editor;
        DefaultBuildSettings = {UE5_BUILD_SETTINGS};
        IncludeOrderVersion = {UE5_INCLUDE_ORDER};
        ExtraModuleNames.Add("{mod}");
    }}
}}
"""


def _module_header(mod: str) -> str:
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#pragma once

#include "CoreMinimal.h"
"""


def _module_cpp(mod: str) -> str:
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#include "{mod}.h"
#include "Modules/ModuleManager.h"

IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, {mod}, "{mod}");
"""


def _game_mode_header(mod: str) -> str:
    cls = f"A{mod}GameMode"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "{mod}GameMode.generated.h"

/**
 *  {cls} — the game mode for {mod}.
 *  Sets the default pawn class, player controller, and HUD.
 *  Generated by Axiom Studio from the game brief.
 */
UCLASS()
class {mod.upper()}_API {cls} : public AGameModeBase
{{
    GENERATED_BODY()

public:
    {cls}();

protected:
    // Called when the game starts
    virtual void BeginPlay() override;
}};
"""


def _game_mode_cpp(mod: str) -> str:
    cls = f"A{mod}GameMode"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#include "{mod}GameMode.h"
#include "{mod}Character.h"
#include "{mod}PlayerController.h"
#include "{mod}HUD.h"
#include "Kismet/GameplayStatics.h"

{cls}::{cls}()
{{
    // Set the default pawn class, player controller, and HUD
    static ConstructorHelpers::FClassFinder<APawn> PlayerPawnBPClass(
        TEXT("/Game/Blueprints/BP_{mod}Character"));
    if (PlayerPawnBPClass.Class != nullptr)
    {{
        DefaultPawnClass = PlayerPawnBPClass.Class;
    }}
    else
    {{
        DefaultPawnClass = A{mod}Character::StaticClass();
    }}

    PlayerControllerClass = A{mod}PlayerController::StaticClass();
    HUDClass = A{mod}HUD::StaticClass();
}}

void {cls}::BeginPlay()
{{
    Super::BeginPlay();

    UE_LOG(LogTemp, Warning, TEXT("{mod} Game Mode started — built by Axiom Studio"));
}}
"""


def _character_header(mod: str) -> str:
    cls = f"A{mod}Character"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "InputActionValue.h"
#include "{mod}Character.generated.h"

class UInputMappingContext;
class UInputAction;
class USpringArmComponent;
class UCameraComponent;

/**
 *  {cls} — the player character for {mod}.
 *  Third-person camera, Enhanced Input movement, jump.
 */
UCLASS()
class {mod.upper()}_API {cls} : public ACharacter
{{
    GENERATED_BODY()

public:
    {cls}()

protected:
    virtual void BeginPlay() override;
    virtual void SetupPlayerInputComponent(
        UInputComponent* PlayerInputComponent) override;

    // Enhanced Input
    UPROPERTY(EditAnywhere, Category = "Input")
    UInputMappingContext* DefaultMappingContext;

    UPROPERTY(EditAnywhere, Category = "Input")
    UInputAction* MoveAction;

    UPROPERTY(EditAnywhere, Category = "Input")
    UInputAction* LookAction;

    UPROPERTY(EditAnywhere, Category = "Input")
    UInputAction* JumpAction;

    // Camera boom + follow camera
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Camera")
    USpringArmComponent* CameraBoom;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Camera")
    UCameraComponent* FollowCamera;

    void Move(const FInputActionValue& Value);
    void Look(const FInputActionValue& Value);
}};
"""


def _character_cpp(mod: str) -> str:
    cls = f"A{mod}Character"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#include "{mod}Character.h"
#include "Components/CapsuleComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/Controller.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"

{cls}::{cls}()
{{
    // Set size for collision capsule
    GetCapsuleComponent()->InitCapsuleSize(42.f, 96.0f);

    // Don't rotate when the controller rotates
    bUseControllerRotationPitch = false;
    bUseControllerRotationYaw = false;
    bUseControllerRotationRoll = false;

    // Camera boom (third person)
    CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
    CameraBoom->SetupAttachment(RootComponent);
    CameraBoom->TargetArmLength = 400.0f;
    CameraBoom->bUsePawnControlRotation = true;

    // Follow camera
    FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));
    FollowCamera->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);
    FollowCamera->bUsePawnControlRotation = false;
}}

void {cls}::BeginPlay()
{{
    Super::BeginPlay();

    // Add the input mapping context
    if (APlayerController* PlayerController = Cast<APlayerController>(Controller))
    {{
        if (UEnhancedInputLocalPlayerSubsystem* Subsystem =
            ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(
                PlayerController->GetLocalPlayer()))
        {{
            Subsystem->AddMappingContext(DefaultMappingContext, 0);
        }}
    }}
}}

void {cls}::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{{
    if (UEnhancedInputComponent* EnhancedInputComponent =
        Cast<UEnhancedInputComponent>(PlayerInputComponent))
    {{
        EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &{cls}::Move);
        EnhancedInputComponent->BindAction(LookAction, ETriggerEvent::Triggered, this, &{cls}::Look);
    }}
    else
    {{
        Super::SetupPlayerInputComponent(PlayerInputComponent);
    }}
}}

void {cls}::Move(const FInputActionValue& Value)
{{
    const FVector2D MovementVector = Value.Get<FVector2D>();
    if (Controller != nullptr)
    {{
        const FRotator Rotation = Controller->GetControlRotation();
        const FRotator YawRotation(0, Rotation.Yaw, 0);
        const FVector ForwardDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X);
        const FVector RightDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y);
        AddMovementInput(ForwardDirection, MovementVector.Y);
        AddMovementInput(RightDirection, MovementVector.X);
    }}
}}

void {cls}::Look(const FInputActionValue& Value)
{{
    const FVector2D LookAxisVector = Value.Get<FVector2D>();
    if (Controller != nullptr)
    {{
        AddControllerYawInput(LookAxisVector.X);
        AddControllerPitchInput(LookAxisVector.Y);
    }}
}}
"""


def _pc_header(mod: str) -> str:
    cls = f"A{mod}PlayerController"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PlayerController.h"
#include "{mod}PlayerController.generated.h"

/**
 *  {cls} — handles player input + gameplay interaction.
 */
UCLASS()
class {mod.upper()}_API {cls} : public APlayerController
{{
    GENERATED_BODY()

protected:
    virtual void BeginPlay() override;
}};
"""


def _pc_cpp(mod: str) -> str:
    cls = f"A{mod}PlayerController"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#include "{mod}PlayerController.h"

void {cls}::BeginPlay()
{{
    Super::BeginPlay();
    UE_LOG(LogTemp, Log, TEXT("{mod} Player Controller active"));
}}
"""


def _hud_header(mod: str) -> str:
    cls = f"A{mod}HUD"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/HUD.h"
#include "{mod}HUD.generated.h"

/**
 *  {cls} — on-screen HUD for {mod}.
 *  Slate-based crosshair + status display, extensible to UMG widgets.
 */
UCLASS()
class {mod.upper()}_API {cls} : public AHUD
{{
    GENERATED_BODY()

protected:
    virtual void DrawHUD() override;
}};
"""


def _hud_cpp(mod: str) -> str:
    cls = f"A{mod}HUD"
    return f"""// Generated by Axiom Studio — UE5.7 C++ scaffold
#include "{mod}HUD.h"
#include "Engine/Canvas.h"
#include "Engine/Engine.h"

void {cls}::DrawHUD()
{{
    Super::DrawHUD();
    // Crosshair
    if (Canvas != nullptr)
    {{
        const FVector2D Center(Canvas->ClipX * 0.5f, Canvas->ClipY * 0.5f);
        const float Size = 8.0f;
        FCanvasLineItem Line1(Center - FVector2D(Size, 0), Center + FVector2D(Size, 0));
        FCanvasLineItem Line2(Center - FVector2D(0, Size), Center + FVector2D(0, Size));
        Line1.SetColor(FLinearColor::Green);
        Line2.SetColor(FLinearColor::Green);
        Canvas->DrawItem(Line1);
        Canvas->DrawItem(Line2);
    }}
}}
"""


# ── Config INI templates ────────────────────────────────────────────────

def _default_engine_ini(mod: str) -> str:
    return f"""[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/L_Startup

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=False
r.ScreenPercentage=200
r.MaxAnisotropy=16
r.Lumen.TranslucencyVolumeSinkDistance=10000
r.Upscale.Sharpness=1.0
r.MaxScreenPercentage=400

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
-D3D11TargetedShaderFormats=PCD3D_SM5
+D3D11TargetedShaderFormats=PCD3D_SM5
Compiler=Default
AudioSampleRate=48000
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=1
AudioMaxChannels=0
AudioNumSourceWorkers=4
SpatializationPlugin=
SourceDataOverridePlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
CacheSizeKB=65536
MaxChunkSizeOverrideKB=0
bResampleForDevice=False
MaxSampleRate=48000.000000
HighSampleRate=32000.000000
MedSampleRate=24000.000000
LowSampleRate=12000.000000
MinSampleRate=8000.000000
CompressionQualityModifier=1.000000
AutoStreamingThreshold=0.000000
SoundCueCookQualityIndex=-1

[/Script/Engine.UserInterfaceSettings]
RenderFocusRule=Navigation
ApplicationScale=1.000000
UIScaleCurve=(EditorCurveData=(Keys=,PreInfinityExtrap=RCCE_Constant,PostInfinityExtrap=RCCE_Constant,DefaultValue=340282346638528859811704183484516925440.PNG, )),UIScaleCurveDomain=(Min=(X=0,Y=0),Max=(X=1,Y=1))

[/Script/Engine.GarbageCollectionSettings]
gc.GatherReferencesBetweenFrame=0
"""


def _default_game_ini(mod: str) -> str:
    return f"""[/Script/EngineSettings.GeneralProjectSettings]
ProjectID={{GENERATED}}
ProjectName={mod}
ProjectVersion=1.0.0
CompanyName=Axiom Studio
CopyrightNotice=Generated by Axiom Studio
Description=AAA game project scaffolded by Axiom Studio

[/Script/Engine.AssetManagerSettings]
CookOnTheFly_CookedPackagesCacheSizeMB=4096
"""


def _default_input_ini(mod: str) -> str:
    return f"""[/Script/Engine.InputSettings]
DefaultViewportMouseCaptureMode=CapturePermanently_IncludingInitialMouseDown
DefaultViewportMouseLockMode=LockOnCapture
bUseMouseForTouch=True
bEnableInputTouchScale=True
"""


# ── .uproject ──────────────────────────────────────────────────────────

def _uproject(mod: str, title: str, description: str, plugin_list: List[str]) -> str:
    plugins = [
        {"Name": p, "Enabled": True, "TargetAllowList": ["Editor"]} for p in plugin_list
    ]
    return json.dumps({
        "FileVersion": 3,
        "EngineAssociation": UE5_ENGINE_ASSOCIATION,
        "Category": "AAA",
        "Description": (description or f"{title} — built by Axiom Studio")[:500],
        "Modules": [
            {"Name": mod, "Type": "Runtime", "LoadingPhase": "Default"}
        ],
        "Plugins": plugins,
    }, indent=4)


# ── The adapter ────────────────────────────────────────────────────────

class UE5CppAdapter(Adapter):
    """Scaffold a real compiling Unreal Engine 5.7 C++ project.

    Always available (local scaffolding, no keys). Triggers a real UBT
    compile at build time if ``UE5_BUILD_ON_SCAFFOLD=1`` is set.
    """
    capability = "engine_project"
    provider = Provider.UE5
    requires_env: List[str] = []  # local
    est_unit_cost_usd = 0.0

    def available(self) -> bool:
        return True  # scaffolding is always available

    def _real(self, prompt: str, workdir: Path, **kwargs) -> Tuple[List[str], str]:
        engine = kwargs.get("engine", "ue5")
        if engine != "ue5":
            # Fall back to the legacy minimal scaffold for non-UE5 engines
            return self._legacy_scaffold(prompt, workdir, **kwargs)

        return self._scaffold_ue5(prompt, workdir, **kwargs)

    def _scaffold_ue5(self, prompt: str, workdir: Path,
                      **kwargs) -> Tuple[List[str], str]:
        title = kwargs.get("title", "AxiomGame")
        mod = _slug(title)
        proj_id = _upid(title)
        proj_dir = workdir / "ue5_project" / proj_id
        src_dir = proj_dir / "Source" / mod

        # Create directory tree
        (proj_dir / "Content").mkdir(parents=True, exist_ok=True)
        (proj_dir / "Config").mkdir(parents=True, exist_ok=True)
        (proj_dir / "Source").mkdir(parents=True, exist_ok=True)
        src_dir.mkdir(parents=True, exist_ok=True)

        artifacts: List[str] = []

        def _write(rel: str, content: str) -> None:
            p = proj_dir / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            artifacts.append(str(p))

        # — .uproject —
        plugins = kwargs.get("plugins", ["ModelingToolsEditorMode"])
        _write(f"{proj_id}.uproject",
               _uproject(mod, title, prompt, plugins))

        # — Target files —
        _write(f"Source/{mod}Target.Target.cs", _game_target(mod))
        _write(f"Source/{mod}EditorTarget.Target.cs", _editor_target(mod))

        # — Build.cs —
        _write(f"Source/{mod}/{mod}.Build.cs", _build_cs(mod))

        # — Module primary files —
        _write(f"Source/{mod}/{mod}.h", _module_header(mod))
        _write(f"Source/{mod}/{mod}.cpp", _module_cpp(mod))

        # — Gameplay classes —
        _write(f"Source/{mod}/{mod}GameMode.h", _game_mode_header(mod))
        _write(f"Source/{mod}/{mod}GameMode.cpp", _game_mode_cpp(mod))
        _write(f"Source/{mod}/{mod}Character.h", _character_header(mod))
        _write(f"Source/{mod}/{mod}Character.cpp", _character_cpp(mod))
        _write(f"Source/{mod}/{mod}PlayerController.h", _pc_header(mod))
        _write(f"Source/{mod}/{mod}PlayerController.cpp", _pc_cpp(mod))
        _write(f"Source/{mod}/{mod}HUD.h", _hud_header(mod))
        _write(f"Source/{mod}/{mod}HUD.cpp", _hud_cpp(mod))

        # — Config —
        _write("Config/DefaultEngine.ini", _default_engine_ini(mod))
        _write("Config/DefaultGame.ini", _default_game_ini(mod))
        _write("Config/DefaultInput.ini", _default_input_ini(mod))

        # — README with build instructions —
        build_cmd = (
            f'"{UE5_ENGINE_ROOT}\\Engine\\Build\\BatchFiles\\Build.bat" '
            f"{mod}Editor Win64 Development "
            f'-Project="{proj_dir / (proj_id + ".uproject")}"'
        )
        uproject_path = str(proj_dir / (proj_id + ".uproject"))
        editor_exe = UE5_ENGINE_ROOT + r"\Engine\Binaries\Win64\UnrealEditor.exe"
        readme = (
            f"# {title}\n\n"
            f"Real UE 5.7 C++ project — scaffolded by **Axiom Studio**.\n\n"
            f"## Module\n`{mod}`\n\n"
            f"## Classes\n"
            f"- `{mod}GameMode` — game mode (default pawn + HUD wiring)\n"
            f"- `{mod}Character` — third-person character, Enhanced Input\n"
            f"- `{mod}PlayerController` — player controller\n"
            f"- `{mod}HUD` — Slate crosshair + status display\n\n"
            f"## Build (from terminal)\n```bat\n{build_cmd}\n```\n\n"
            f"## Open in editor\n```bat\n"
            f'"{editor_exe}" "{uproject_path}"\n'
            f"```\n\n"
            f"## Brief\n{prompt}\n"
        )
        _write("README.md", readme)

        # Optionally compile immediately
        built = False
        if os.environ.get("UE5_BUILD_ON_SCAFFOLD", "").strip().lower() in (
            "1", "true", "yes", "on"
        ):
            built = self._try_compile(proj_dir, proj_id, mod)

        notes = f"UE5.7 C++ project scaffolded ({len(artifacts)} files, module={mod})"
        if built:
            notes += " + COMPILED OK"
        return artifacts, notes

    def _legacy_scaffold(self, prompt: str, workdir: Path,
                          **kwargs) -> Tuple[List[str], str]:
        """Minimal scaffold for non-UE5 engines (Unity / Godot)."""
        engine = kwargs.get("engine", "ue5")
        proj = workdir / f"{engine}_project"
        proj.mkdir(parents=True, exist_ok=True)
        (proj / "README.md").write_text(
            f"# {kwargs.get('title', 'Game')} ({engine})\n\n{prompt}\n",
            encoding="utf-8",
        )
        return [str(proj)], f"{engine} legacy scaffold"

    def _try_compile(self, proj_dir: Path, proj_id: str, mod: str) -> bool:
        """Attempt a real UBT compile. Returns True on success."""
        import subprocess
        build_bat = f"{UE5_ENGINE_ROOT}\\Engine\\Build\\BatchFiles\\Build.bat"
        if not Path(build_bat).is_file():
            return False
        proj_path = proj_dir / f"{proj_id}.uproject"
        cmd = [
            build_bat,
            f"{mod}Editor",
            "Win64",
            "Development",
            f'-Project="{proj_path}"',
        ]
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                timeout=1800,
            )
            return result.returncode == 0
        except Exception:
            return False


# ── Register at priority 90 — higher than the legacy EngineProjectAdapter(50) ──
default_registry.register(UE5CppAdapter(), priority=90)
