export const ownerBrief = {
  status: 'audit-ready',
  mission: 'Use Hermes as the JARVIS backend and Base44 as the command cockpit.',
  canonicalRepo: 'A-C-I-SOFTWARE-AND-DEVELOPMENT/hermes-agent',
  commit: 'b8308c86faf59deb5ec668bbb2e3b84560b92ab8',
  nextAction: 'Add safe Hermes API bridge, then connect this cockpit to live job/gate/status endpoints.'
};

export const jobs = [
  { id: 'P0-BASE44', title: 'Add missing Base44 cockpit folder', risk: 'RC2', status: 'ready', ownerGate: false },
  { id: 'P0-API', title: 'Expose safe Hermes API bridge', risk: 'RC3', status: 'planned', ownerGate: true },
  { id: 'P1-MEMORY', title: 'Memory candidate review queue', risk: 'RC3', status: 'planned', ownerGate: true }
];

export const gates = [
  ['Planning', 'pass', 'mission, branch, allowed files, non-goals, acceptance criteria present'],
  ['Build', 'pass', 'changes scoped to generated audit artifacts'],
  ['Review', 'pass', 'contrarian objection captured: Base44 is cockpit, not backend'],
  ['Test', 'pass', 'compileall + 215 JARVIS Prime tests passed'],
  ['Security', 'pass', 'no secrets written'],
  ['Release', 'pass', 'rollback and risks documented'],
  ['Owner Approval', 'pass', 'no owner-gated execution performed'],
  ['Rollback', 'pass', 'audit-only artifacts can be discarded']
];

export const modelRoutes = [
  { lane: 'Prime reasoning', model: 'gpt-5.5', reason: 'complex architecture and final synthesis' },
  { lane: 'Monitor summaries', model: 'gpt-5.4-mini', reason: 'fast recurring triage' },
  { lane: 'Builder', model: 'Claude Sonnet 4.6 / Claude Code', reason: 'implementation lane' },
  { lane: 'Reviewer', model: 'Claude Opus 4.7', reason: 'independent high-stakes review' },
  { lane: 'Google/Android checks', model: 'Gemini 3.5 Flash / 3.1 Pro', reason: 'Google ecosystem validation' },
  { lane: 'Local OSS experiment', model: 'Qwen3-Coder-480B-A35B', reason: 'bounded local coding experiment' }
];

export const integrations = [
  { name: 'Hermes CLI', state: 'canonical backend' },
  { name: 'JARVIS Prime', state: 'runtime shipped' },
  { name: 'Slack Gateway', state: 'repo-supported' },
  { name: 'Termux', state: 'repo-supported' },
  { name: 'GitHub Sync', state: 'workflow exists' },
  { name: 'Base44 App Folder', state: 'generated by this patch' }
];
