# ============================================================================
# NEXUS one-click installer (Windows, PowerShell).
#
#   cd apps\nexus ; .\install.ps1
#
# Installs deps, generates a VAPID keypair, writes .env, builds the PWA, and
# serves it. The in-app "Install & Connect" wizard then establishes the MUSE
# gateway + every other connection autonomously.
# ============================================================================
$ErrorActionPreference = 'Stop'
Set-Location -Path $PSScriptRoot

function Say($m)  { Write-Host "▸ $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "✓ $m" -ForegroundColor Green }
function Warn($m) { Write-Host "! $m" -ForegroundColor Yellow }

$Port        = if ($env:NEXUS_PORT) { $env:NEXUS_PORT } else { '4173' }
$GatewayUrl  = if ($env:MUSE_GATEWAY_URL) { $env:MUSE_GATEWAY_URL } else { 'http://127.0.0.1:8765' }

Say "NEXUS installer — $(Get-Location)"

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Warn 'Node.js not found. Install Node 18+ (https://nodejs.org) and re-run.'
  exit 1
}
Ok "node $(node -v)"

Say 'Installing dependencies…'
if (Test-Path package-lock.json) { npm ci --no-audit --no-fund } else { npm install --no-audit --no-fund }
Ok 'dependencies installed'

if (-not (Test-Path .env)) {
  Say 'Generating .env (VAPID keypair + gateway URL)…'
  $pub = ''
  try {
    $json = npx --yes web-push generate-vapid-keys --json 2>$null | ConvertFrom-Json
    $pub = $json.publicKey
  } catch { Warn 'web-push VAPID generation skipped' }
  @"
# Auto-generated by install.ps1. The in-app wizard can override at runtime.
VITE_MUSE_BASE_URL=$GatewayUrl
VITE_VAPID_PUBLIC_KEY=$pub
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=
"@ | Set-Content -Encoding UTF8 .env
  Ok ".env written (gateway: $GatewayUrl)"
} else {
  Ok '.env already present (left untouched)'
}

Say 'Building PWA…'
npm run build
Ok 'build complete (dist/)'

Say "Serving NEXUS on http://localhost:$Port  (Ctrl+C to stop)"
Say "Open it, then click 'Install & Connect everything' — pairing needs the owner phrase once."
npm run preview -- --host --port $Port
