#!/usr/bin/env bash
# ============================================================================
# NEXUS one-click installer (Linux / macOS / WSL2 / Termux).
#
#   curl -fsSL <raw>/apps/nexus/install.sh | bash
#       — or —
#   cd apps/nexus && ./install.sh
#
# Installs deps, generates a VAPID keypair, writes .env, builds the PWA, and
# serves it. The in-app "Install & Connect" wizard then establishes the MUSE
# gateway + every other connection autonomously. Optionally boots the gateway.
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

say() { printf '\033[36m▸ %s\033[0m\n' "$*"; }
ok()  { printf '\033[32m✓ %s\033[0m\n' "$*"; }
warn(){ printf '\033[33m! %s\033[0m\n' "$*"; }

PORT="${NEXUS_PORT:-4173}"
GATEWAY_URL="${MUSE_GATEWAY_URL:-http://127.0.0.1:8765}"
START_GATEWAY="${START_GATEWAY:-0}"

say "NEXUS installer — $(pwd)"

# 1) Node check
if ! command -v node >/dev/null 2>&1; then
  warn "Node.js not found. Install Node 18+ (https://nodejs.org) and re-run."
  exit 1
fi
ok "node $(node -v)"

# 2) Install dependencies
say "Installing dependencies…"
if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
ok "dependencies installed"

# 3) .env — generate VAPID keys + seed the gateway URL (auto-discovered if blank)
if [ ! -f .env ]; then
  say "Generating .env (VAPID keypair + gateway URL)…"
  VAPID_PUB=""; VAPID_PRIV=""
  if npx --yes web-push generate-vapid-keys --json >/tmp/nexus_vapid.json 2>/dev/null; then
    VAPID_PUB="$(node -e "console.log(require('/tmp/nexus_vapid.json').publicKey)" 2>/dev/null || true)"
    VAPID_PRIV="$(node -e "console.log(require('/tmp/nexus_vapid.json').privateKey)" 2>/dev/null || true)"
    rm -f /tmp/nexus_vapid.json
  fi
  cat > .env <<EOF
# Auto-generated by install.sh. The in-app wizard can override these at runtime.
VITE_MUSE_BASE_URL=$GATEWAY_URL
VITE_VAPID_PUBLIC_KEY=$VAPID_PUB
# VAPID private key lives ONLY on the MUSE gateway, never in the PWA:
# MUSE_VAPID_PRIVATE_KEY=$VAPID_PRIV
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=
EOF
  ok ".env written (gateway: $GATEWAY_URL)"
else
  ok ".env already present (left untouched)"
fi

# 4) Optionally boot the MUSE cockpit gateway (from the repo root, if present)
if [ "$START_GATEWAY" = "1" ]; then
  REPO_ROOT="$(cd "$HERE/../.." && pwd)"
  if [ -f "$REPO_ROOT/gateway/cockpit/server.py" ]; then
    say "Starting MUSE cockpit gateway on 127.0.0.1:8765…"
    ( cd "$REPO_ROOT" && python -m gateway.cockpit.server >/tmp/nexus_gateway.log 2>&1 & )
    sleep 2
    ok "gateway launching (log: /tmp/nexus_gateway.log)"
  else
    warn "gateway/cockpit/server.py not found — skipping gateway boot"
  fi
fi

# 5) Build + serve
say "Building PWA…"
npm run build
ok "build complete (dist/)"

say "Serving NEXUS on http://localhost:$PORT  (Ctrl+C to stop)"
say "Open it, then tap 'Install & Connect everything' — pairing needs the owner phrase once."
exec npm run preview -- --host --port "$PORT"
