#!/usr/bin/env bash
# hermes-ai-radar.sh - Run the AI Improvement Radar.
#
# Tracks AI coding tools (Codex, Claude Code, Aider, Goose, Continue,
# OpenHands, OpenClaw-like, Gemini/Jules-style, etc.) and writes a
# dated report under docs/ai-intelligence/.
#
# Default mode: OFFLINE. The script never reaches the network unless
# you pass --online.
#
# Usage:
#   scripts/hermes-ai-radar.sh                 # offline snapshot
#   scripts/hermes-ai-radar.sh --online        # allow web fetches
#   scripts/hermes-ai-radar.sh --out PATH      # write report to PATH
#   scripts/hermes-ai-radar.sh --dry-run       # print plan, write nothing
#   scripts/hermes-ai-radar.sh -h | --help     # show help

set -euo pipefail

# --- Locate repo root --------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Defaults ----------------------------------------------------------------
MODE="offline"
DRY_RUN=0
OUT_DIR="$REPO_ROOT/docs/ai-intelligence"
OUT_FILE=""
TODAY="$(date -u +%Y-%m-%d)"

usage() {
    sed -n '2,18p' "$0"
}

# --- Parse args --------------------------------------------------------------
while [ "$#" -gt 0 ]; do
    case "$1" in
        --online)
            MODE="online"
            shift
            ;;
        --offline)
            MODE="offline"
            shift
            ;;
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        --out)
            if [ "$#" -lt 2 ]; then
                echo "error: --out requires a path" >&2
                exit 2
            fi
            OUT_FILE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown arg: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

# --- Resolve output path -----------------------------------------------------
if [ -z "$OUT_FILE" ]; then
    OUT_FILE="$OUT_DIR/ai-improvement-radar.md"
fi
HISTORY_DIR="$OUT_DIR/history"
HISTORY_FILE="$HISTORY_DIR/$TODAY-radar.md"

mkdir -p "$OUT_DIR" "$HISTORY_DIR"

# --- Build the report body ---------------------------------------------------
TMP_REPORT="$(mktemp)"
trap 'rm -f "$TMP_REPORT"' EXIT

{
    echo "# AI Radar - $TODAY"
    echo "Mode: $MODE"
    if [ "$MODE" = "offline" ]; then
        echo "Note: offline-snapshot. Re-run with --online to refresh"
        echo "      from primary sources."
    else
        echo "Note: online mode requested. Primary-source fetches must be"
        echo "      performed by an agent that has WebFetch/WebSearch tools."
        echo "      This shell script does not call the network."
    fi
    echo
    echo "## Tracked products"
    echo "- OpenAI Codex / Codex CLI / Responses API"
    echo "- Anthropic Claude Code / Claude Agent SDK / Claude API"
    echo "- Aider"
    echo "- Goose (Block)"
    echo "- Continue"
    echo "- OpenHands (formerly OpenDevin)"
    echo "- OpenClaw-like local-first tools"
    echo "- Google Gemini CLI / Jules-style autonomous agents"
    echo "- Cursor, Windsurf, Zed agentic modes"
    echo
    echo "## Per-product status"
    echo "Each entry must be filled by the radar agent. Mark every claim"
    echo "verified | unverified | stale and cite the primary source."
    echo
    echo "### template"
    echo "- Version: <x.y.z> (verified|unverified|stale)"
    echo "- Released: <date>"
    echo "- New: <bullets>"
    echo "- Regressions: <bullets>"
    echo "- Recommendation: <none | add | promote | demote | remove>"
    echo
    echo "## Routing patches recommended"
    echo "- none"
    echo
    echo "## Open questions"
    echo "- Are any tracked products missing from the list above?"
    echo "- Has the model registry changed since the last radar run?"
    echo
    echo "## Provenance"
    echo "- Generated by scripts/hermes-ai-radar.sh"
    echo "- Repo: $REPO_ROOT"
    echo "- Mode: $MODE"
    echo "- Date (UTC): $TODAY"
} > "$TMP_REPORT"

# --- Write or dry-run --------------------------------------------------------
if [ "$DRY_RUN" -eq 1 ]; then
    echo "DRY RUN - would write the following report to:"
    echo "  $OUT_FILE"
    echo "  $HISTORY_FILE"
    echo "----- begin -----"
    cat "$TMP_REPORT"
    echo "----- end -----"
    exit 0
fi

cp "$TMP_REPORT" "$OUT_FILE"
cp "$TMP_REPORT" "$HISTORY_FILE"

echo "wrote: $OUT_FILE"
echo "wrote: $HISTORY_FILE"

if [ "$MODE" = "offline" ]; then
    echo "mode: offline-snapshot (re-run with --online to refresh)"
fi
