-- Authoritative M.U.S.E network-realm event log, projections, and command RPC.
-- Clients can read only through tenant-safe RLS and can write only through the
-- authenticated execute_universe_command transaction below.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.universe_realms (
  realm_id text primary key,
  owner_user_id uuid not null references auth.users (id) on delete restrict,
  name text not null check (char_length(name) between 1 and 200),
  mode text not null check (mode in ('private', 'team', 'network', 'public')),
  is_public boolean not null default false,
  version bigint not null default 0 check (version >= 0),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.universe_memberships (
  realm_id text not null references public.universe_realms (realm_id) on delete restrict,
  user_id uuid not null references auth.users (id) on delete restrict,
  membership_id text not null,
  player_id text not null,
  status text not null check (status in ('invited', 'active', 'removed')),
  scopes text[] not null default array[]::text[] check (cardinality(scopes) <= 64),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (realm_id, user_id),
  unique (membership_id),
  unique (realm_id, player_id)
);

create table if not exists public.universe_events (
  sequence bigint generated by default as identity primary key,
  event_id text not null unique default gen_random_uuid()::text,
  schema_version integer not null default 1 check (schema_version = 1),
  event_type text not null,
  realm_id text not null references public.universe_realms (realm_id) on delete restrict,
  actor_user_id uuid not null references auth.users (id) on delete restrict,
  actor_id text not null,
  stream_type text not null,
  stream_id text not null,
  stream_version bigint not null check (stream_version > 0),
  authorization jsonb not null check (jsonb_typeof(authorization) = 'object'),
  causation_id text not null,
  correlation_id text not null,
  occurred_at timestamptz not null,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  provenance jsonb not null check (jsonb_typeof(provenance) = 'object'),
  simulation boolean not null default false,
  rollback jsonb not null check (jsonb_typeof(rollback) = 'object'),
  is_public boolean not null default false,
  event jsonb not null check (jsonb_typeof(event) = 'object'),
  unique (stream_type, stream_id, stream_version)
);

create index if not exists universe_events_realm_sequence
  on public.universe_events (realm_id, sequence);
create index if not exists universe_events_realm_stream
  on public.universe_events (realm_id, stream_type, stream_id, stream_version);

create table if not exists public.universe_entities (
  realm_id text not null references public.universe_realms (realm_id) on delete restrict,
  entity_type text not null,
  entity_id text not null,
  version bigint not null check (version > 0),
  is_public boolean not null default false,
  deleted boolean not null default false,
  updated_at timestamptz not null,
  entity jsonb not null check (jsonb_typeof(entity) = 'object'),
  primary key (realm_id, entity_type, entity_id)
);

create index if not exists universe_entities_realm_type
  on public.universe_entities (realm_id, entity_type, entity_id);

create table if not exists public.universe_command_results (
  realm_id text not null references public.universe_realms (realm_id) on delete restrict,
  command_id text not null,
  actor_user_id uuid not null references auth.users (id) on delete restrict,
  command_fingerprint text not null check (command_fingerprint ~ '^[0-9a-f]{64}$'),
  event_id text not null references public.universe_events (event_id) on delete restrict,
  result jsonb not null check (jsonb_typeof(result) = 'object'),
  created_at timestamptz not null default now(),
  primary key (realm_id, command_id)
);

-- Bound approvals are service-authored records consumed atomically by the RPC.
-- No browser or authenticated client role receives direct write access.
create table if not exists public.universe_approval_grants (
  approval_id text primary key,
  realm_id text not null references public.universe_realms (realm_id) on delete restrict,
  actor_user_id uuid not null references auth.users (id) on delete restrict,
  action text not null,
  correlation_id text not null,
  subject_hash text not null check (subject_hash ~ '^[0-9a-f]{64}$'),
  state text not null check (state in ('approved', 'consumed', 'revoked')),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  consumed_at timestamptz
);

create index if not exists universe_approvals_realm_actor
  on public.universe_approval_grants (realm_id, actor_user_id, state, expires_at);

alter table public.universe_realms enable row level security;
alter table public.universe_realms force row level security;
alter table public.universe_memberships enable row level security;
alter table public.universe_memberships force row level security;
alter table public.universe_events enable row level security;
alter table public.universe_events force row level security;
alter table public.universe_entities enable row level security;
alter table public.universe_entities force row level security;
alter table public.universe_command_results enable row level security;
alter table public.universe_command_results force row level security;
alter table public.universe_approval_grants enable row level security;
alter table public.universe_approval_grants force row level security;

create or replace function public.universe_is_active_member(p_realm_id text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select auth.uid() is not null and exists (
    select 1
    from public.universe_memberships membership
    where membership.realm_id = p_realm_id
      and membership.user_id = auth.uid()
      and membership.status = 'active'
  );
$$;

create or replace function public.universe_is_realm_owner(p_realm_id text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select auth.uid() is not null and exists (
    select 1
    from public.universe_realms realm
    where realm.realm_id = p_realm_id
      and realm.owner_user_id = auth.uid()
  );
$$;

create or replace function public.universe_realm_is_public(p_realm_id text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1
    from public.universe_realms realm
    where realm.realm_id = p_realm_id
      and realm.is_public
  );
$$;

revoke all on function public.universe_is_active_member(text) from public;
revoke all on function public.universe_is_realm_owner(text) from public;
revoke all on function public.universe_realm_is_public(text) from public;
grant execute on function public.universe_is_active_member(text) to anon, authenticated;
grant execute on function public.universe_is_realm_owner(text) to anon, authenticated;
grant execute on function public.universe_realm_is_public(text) to anon, authenticated;

drop policy if exists universe_realms_select_visible on public.universe_realms;
create policy universe_realms_select_visible on public.universe_realms
  for select to anon, authenticated
  using (
    is_public
    or public.universe_is_realm_owner(realm_id)
    or public.universe_is_active_member(realm_id)
  );

drop policy if exists universe_memberships_select_tenant on public.universe_memberships;
create policy universe_memberships_select_tenant on public.universe_memberships
  for select to authenticated
  using (
    user_id = auth.uid()
    or public.universe_is_realm_owner(realm_id)
    or public.universe_is_active_member(realm_id)
  );

drop policy if exists universe_events_select_tenant_or_public on public.universe_events;
create policy universe_events_select_tenant_or_public on public.universe_events
  for select to anon, authenticated
  using (
    public.universe_is_realm_owner(realm_id)
    or public.universe_is_active_member(realm_id)
    or (is_public and public.universe_realm_is_public(realm_id))
  );

drop policy if exists universe_entities_select_tenant_or_public on public.universe_entities;
create policy universe_entities_select_tenant_or_public on public.universe_entities
  for select to anon, authenticated
  using (
    public.universe_is_realm_owner(realm_id)
    or public.universe_is_active_member(realm_id)
    or (is_public and public.universe_realm_is_public(realm_id))
  );

drop policy if exists universe_command_results_select_own on public.universe_command_results;
create policy universe_command_results_select_own on public.universe_command_results
  for select to authenticated
  using (
    actor_user_id = auth.uid()
    and (
      public.universe_is_realm_owner(realm_id)
      or public.universe_is_active_member(realm_id)
    )
  );

drop policy if exists universe_approval_grants_select_own on public.universe_approval_grants;
create policy universe_approval_grants_select_own on public.universe_approval_grants
  for select to authenticated
  using (
    actor_user_id = auth.uid()
    and (
      public.universe_is_realm_owner(realm_id)
      or public.universe_is_active_member(realm_id)
    )
  );

revoke all on table public.universe_realms from anon, authenticated;
revoke all on table public.universe_memberships from anon, authenticated;
revoke all on table public.universe_events from anon, authenticated;
revoke all on table public.universe_entities from anon, authenticated;
revoke all on table public.universe_command_results from anon, authenticated;
revoke all on table public.universe_approval_grants from anon, authenticated;

grant select (
  realm_id, name, mode, is_public, version, metadata, created_at, updated_at
) on table public.universe_realms to anon, authenticated;
grant select on table public.universe_memberships to authenticated;
grant select (
  sequence, event_id, schema_version, event_type, realm_id, actor_id,
  stream_type, stream_id, stream_version, causation_id, correlation_id,
  occurred_at, simulation, is_public, event
) on table public.universe_events to anon, authenticated;
grant select on table public.universe_entities to anon, authenticated;
grant select (
  realm_id, command_id, command_fingerprint, event_id, result, created_at
) on table public.universe_command_results to authenticated;
grant select (
  approval_id, realm_id, action, correlation_id, subject_hash, state,
  expires_at, created_at, consumed_at
) on table public.universe_approval_grants to authenticated;

revoke insert, update, delete, truncate
  on table public.universe_realms,
    public.universe_memberships,
    public.universe_events,
    public.universe_entities,
    public.universe_command_results,
    public.universe_approval_grants
  from anon, authenticated;
revoke insert, update, delete on public.universe_events from anon, authenticated;

create or replace function public.reject_universe_event_update()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  raise exception using errcode = '55000', message = 'universe events are immutable';
end;
$$;

create or replace function public.reject_universe_event_delete()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  raise exception using errcode = '55000', message = 'universe events are append-only';
end;
$$;

drop trigger if exists prevent_universe_event_update on public.universe_events;
create trigger prevent_universe_event_update
  before update on public.universe_events
  for each row execute function public.reject_universe_event_update();

drop trigger if exists prevent_universe_event_delete on public.universe_events;
create trigger prevent_universe_event_delete
  before delete on public.universe_events
  for each row execute function public.reject_universe_event_delete();

create or replace function public.universe_json_has_forbidden_keys(p_value jsonb)
returns boolean
language plpgsql
immutable
set search_path = pg_catalog, public
as $$
declare
  item record;
  normalized text;
begin
  if jsonb_typeof(p_value) = 'object' then
    for item in select key, value from jsonb_each(p_value)
    loop
      normalized := lower(regexp_replace(item.key, '[^a-zA-Z0-9]+', '', 'g'));
      if normalized in (
        'apikey', 'authorization', 'ownerauthorization', 'ownerphrase',
        'privatekey', 'providerkey', 'token'
      ) or normalized ~ '(bearer|cookie|credential|password|passwd|secret)'
        or normalized ~ 'token$'
      then
        return true;
      end if;
      if public.universe_json_has_forbidden_keys(item.value) then
        return true;
      end if;
    end loop;
  elsif jsonb_typeof(p_value) = 'array' then
    for item in select value from jsonb_array_elements(p_value)
    loop
      if public.universe_json_has_forbidden_keys(item.value) then
        return true;
      end if;
    end loop;
  end if;
  return false;
end;
$$;

create or replace function public.universe_command_spec(p_command_type text)
returns table (
  stream_type text,
  event_type text,
  required_scope text,
  approval_required boolean,
  public_capable boolean,
  simulation_forbidden boolean
)
language plpgsql
immutable
set search_path = pg_catalog, public
as $$
begin
  case p_command_type
    when 'realm.create' then return query select 'realm', 'realm.created', 'realm:create', false, false, false;
    when 'player.create' then return query select 'player', 'player.created', 'player:write', false, false, false;
    when 'civilization.create' then return query select 'civilization', 'civilization.created', 'civilization:write', false, false, false;
    when 'membership.invite' then return query select 'membership', 'membership.invited', 'membership:invite', false, false, false;
    when 'membership.accept' then return query select 'membership', 'membership.accepted', 'membership:accept', false, false, false;
    when 'presence.update' then return query select 'presence', 'presence.updated', 'presence:write', false, false, false;
    when 'governance.propose' then return query select 'proposal', 'governance.proposed', 'governance:propose', false, false, false;
    when 'governance.vote' then return query select 'proposal', 'governance.vote_recorded', 'governance:vote', false, false, false;
    when 'governance.execute' then return query select 'proposal', 'governance.executed', 'governance:execute', false, false, false;
    when 'civilization.diplomacy' then return query select 'treaty', 'diplomacy.updated', 'diplomacy:write', false, false, false;
    when 'moderation.report' then return query select 'moderation_case', 'moderation.reported', 'moderation:report', false, false, false;
    when 'moderation.block' then return query select 'block', 'moderation.blocked', 'moderation:block', false, false, false;
    when 'station.create' then return query select 'station', 'station.created', 'station:write', false, false, false;
    when 'world.create' then return query select 'world', 'world.created', 'world:write', false, false, false;
    when 'world.region.freeze' then return query select 'world', 'world.region_frozen', 'world:freeze', false, false, false;
    when 'world.region.regenerate' then return query select 'world', 'world.region_regenerated', 'world:regenerate', true, false, false;
    when 'building.place' then return query select 'building', 'building.placed', 'building:write', false, false, false;
    when 'vessel.create' then return query select 'vessel', 'vessel.created', 'vessel:write', false, false, false;
    when 'vessel.module.install' then return query select 'vessel', 'vessel.module_installed', 'vessel:configure', true, false, true;
    when 'vessel.cosmetics.update' then return query select 'vessel', 'vessel.cosmetics_updated', 'vessel:cosmetics', false, false, false;
    when 'fleet.create' then return query select 'fleet', 'fleet.created', 'fleet:write', false, false, false;
    when 'fleet.assign' then return query select 'fleet', 'fleet.member_assigned', 'fleet:assign', false, false, false;
    when 'mission.create' then return query select 'mission', 'mission.created', 'mission:write', false, false, false;
    when 'mission.transition' then return query select 'mission', 'mission.transitioned', 'mission:transition', false, false, false;
    when 'campaign.create' then return query select 'campaign', 'campaign.created', 'campaign:write', false, false, false;
    when 'expedition.create' then return query select 'expedition', 'expedition.created', 'expedition:write', false, false, false;
    when 'blueprint.publish' then return query select 'blueprint', 'blueprint.published', 'blueprint:publish', false, true, true;
    when 'exchange.listing.publish' then return query select 'exchange_listing', 'exchange.listing_published', 'exchange:publish', true, true, true;
    when 'exchange.listing.remove' then return query select 'exchange_listing', 'exchange.listing_removed', 'exchange:remove', true, false, true;
    when 'marketplace.refund' then return query select 'creator_ledger', 'marketplace.refunded', 'marketplace:refund', true, false, true;
    when 'gallery.publish' then return query select 'gallery_item', 'gallery.published', 'gallery:publish', false, true, true;
    when 'asset.register' then return query select 'asset', 'asset.registered', 'asset:register', true, true, true;
    when 'operational_ledger.record' then return query select 'operational_ledger', 'operational.recorded', 'operational:record', false, false, true;
    when 'creator_ledger.record' then return query select 'creator_ledger', 'creator.recorded', 'creator:record', false, false, true;
    when 'creator_ledger.transfer' then return query select 'creator_ledger', 'creator.transferred', 'creator:transfer', false, false, true;
    when 'logistics.update' then return query select 'logistics', 'logistics.updated', 'logistics:write', false, false, false;
    when 'workspace.lease' then return query select 'workspace_lease', 'workspace.leased', 'workspace:lease', true, false, true;
    when 'release.stage' then return query select 'release', 'release.staged', 'release:stage', false, false, true;
    when 'release.promote' then return query select 'release', 'release.promoted', 'release:promote', true, false, true;
    when 'cinematic_shot.create' then return query select 'cinematic_shot', 'cinematic_shot.created', 'cinematic:write', false, false, false;
    when 'cinematic_shot.qc' then return query select 'cinematic_shot', 'cinematic_shot.qc_recorded', 'cinematic:qc', false, false, false;
    else return;
  end case;
end;
$$;

create or replace function public.universe_required_scope(p_command_type text)
returns text
language sql
immutable
set search_path = pg_catalog, public
as $$
  select descriptor.required_scope
  from public.universe_command_spec(p_command_type) as descriptor
  limit 1;
$$;

create or replace function public.universe_command_descriptor(p_command_type text)
returns jsonb
language sql
immutable
set search_path = pg_catalog, public
as $$
  select to_jsonb(descriptor)
  from public.universe_command_spec(p_command_type) as descriptor
  limit 1;
$$;

revoke all on function public.universe_json_has_forbidden_keys(jsonb) from public, anon, authenticated;
revoke all on function public.universe_command_spec(text) from public, anon, authenticated;
revoke all on function public.universe_required_scope(text) from public, anon, authenticated;
revoke all on function public.universe_command_descriptor(text) from public, anon, authenticated;

create or replace function public.execute_universe_command(p_command jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_command_id text;
  v_command_type text;
  v_realm_id text;
  v_stream_id text;
  v_stream_type text;
  v_event_type text;
  v_required_scope text;
  v_approval_required boolean;
  v_public_capable boolean;
  v_simulation_forbidden boolean;
  v_expected_version bigint;
  v_current_version bigint := 0;
  v_payload jsonb;
  v_current_entity jsonb := '{}'::jsonb;
  v_entity jsonb;
  v_event jsonb;
  v_result jsonb;
  v_stored_result jsonb;
  v_stored_fingerprint text;
  v_stored_actor uuid;
  v_command_fingerprint text;
  v_actor_id text;
  v_membership_id text;
  v_membership_status text;
  v_scopes text[] := array[]::text[];
  v_is_owner boolean := false;
  v_realm_public boolean := false;
  v_current_public boolean := false;
  v_is_public boolean := false;
  v_simulation boolean := false;
  v_needs_approval boolean := false;
  v_approval_id text;
  v_subject_hash text;
  v_causation_id text;
  v_correlation_id text;
  v_event_id text := gen_random_uuid()::text;
  v_sequence bigint;
  v_occurred_at timestamptz := clock_timestamp();
  v_authorization jsonb;
  v_provenance jsonb;
  v_target_user_id uuid;
  v_target_player_id text;
  v_target_scopes text[];
  v_rows integer;
begin
  if v_user_id is null then
    raise exception using errcode = 'P0001', message = 'universe_unauthorized';
  end if;
  if p_command is null or jsonb_typeof(p_command) <> 'object' then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if pg_column_size(p_command) > 65536
    or not (p_command ?& array[
      'command_id', 'command_type', 'realm_id', 'stream_id',
      'expected_version', 'payload'
    ])
  then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if p_command ? 'actor_id' then
    raise exception using
      errcode = 'P0001',
      message = 'universe_invalid_command',
      detail = 'MUSE_ACTOR_MISMATCH';
  end if;
  if p_command ?| array[
    'authorization', 'owner_authorization', 'provenance',
    'roles', 'scopes', 'stream_type'
  ] then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if exists (
    select 1
    from jsonb_object_keys(p_command) as field(key)
    where not (field.key = any (array[
      'command_id', 'command_type', 'realm_id', 'stream_id',
      'expected_version', 'payload', 'causation_id', 'correlation_id',
      'approval_id', 'simulation'
    ]::text[]))
  ) then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;

  v_command_id := p_command ->> 'command_id';
  v_command_type := p_command ->> 'command_type';
  v_realm_id := p_command ->> 'realm_id';
  v_stream_id := p_command ->> 'stream_id';
  if jsonb_typeof(p_command -> 'command_id') <> 'string'
    or jsonb_typeof(p_command -> 'command_type') <> 'string'
    or jsonb_typeof(p_command -> 'realm_id') <> 'string'
    or jsonb_typeof(p_command -> 'stream_id') <> 'string'
    or v_command_id is null or v_command_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
    or v_realm_id is null or v_realm_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
    or v_stream_id is null or v_stream_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
  then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if p_command ? 'causation_id' and jsonb_typeof(p_command -> 'causation_id') <> 'string'
    or p_command ? 'correlation_id' and jsonb_typeof(p_command -> 'correlation_id') <> 'string'
    or p_command ? 'approval_id' and jsonb_typeof(p_command -> 'approval_id') <> 'string'
  then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  v_causation_id := coalesce(nullif(p_command ->> 'causation_id', ''), v_command_id);
  v_correlation_id := coalesce(nullif(p_command ->> 'correlation_id', ''), v_command_id);
  v_approval_id := nullif(p_command ->> 'approval_id', '');
  if v_causation_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
    or v_correlation_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
    or (v_approval_id is not null and v_approval_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$')
  then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if jsonb_typeof(p_command -> 'expected_version') <> 'number'
    or (p_command ->> 'expected_version') !~ '^(0|[1-9][0-9]*)$'
    or char_length(p_command ->> 'expected_version') > 16
  then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  v_expected_version := (p_command ->> 'expected_version')::bigint;
  if v_expected_version > 9007199254740991 then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if jsonb_typeof(p_command -> 'payload') <> 'object'
    or public.universe_json_has_forbidden_keys(p_command -> 'payload')
  then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  v_payload := p_command -> 'payload';
  if v_payload ? 'id' and (jsonb_typeof(v_payload -> 'id') <> 'string' or v_payload ->> 'id' <> v_stream_id) then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if v_payload ? 'deleted' and jsonb_typeof(v_payload -> 'deleted') <> 'boolean' then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if p_command ? 'simulation' and jsonb_typeof(p_command -> 'simulation') <> 'boolean' then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  v_simulation := coalesce((p_command ->> 'simulation')::boolean, false);

  select spec.stream_type, spec.event_type, spec.required_scope,
         spec.approval_required, spec.public_capable, spec.simulation_forbidden
    into v_stream_type, v_event_type, v_required_scope,
         v_approval_required, v_public_capable, v_simulation_forbidden
  from public.universe_command_spec(v_command_type) as spec;
  if not found then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if v_command_type = 'realm.create' and v_stream_id <> v_realm_id then
    raise exception using errcode = 'P0001', message = 'universe_invalid_command';
  end if;
  if v_simulation and v_simulation_forbidden then
    raise exception using errcode = 'P0001', message = 'universe_forbidden';
  end if;

  v_command_fingerprint := encode(
    digest(convert_to(p_command::text, 'UTF8'), 'sha256'),
    'hex'
  );
  perform pg_advisory_xact_lock(
    hashtextextended('universe-command:' || v_realm_id || ':' || v_command_id, 0)
  );
  select command.result, command.command_fingerprint, command.actor_user_id
    into v_stored_result, v_stored_fingerprint, v_stored_actor
  from public.universe_command_results command
  where command.realm_id = v_realm_id and command.command_id = v_command_id;
  if found then
    if v_stored_fingerprint <> v_command_fingerprint or v_stored_actor <> v_user_id then
      raise exception using errcode = 'P0001', message = 'universe_command_id_conflict';
    end if;
    select realm.owner_user_id = v_user_id
      into v_is_owner
    from public.universe_realms realm
    where realm.realm_id = v_realm_id;
    if not found then
      raise exception using errcode = 'P0001', message = 'universe_not_found';
    end if;
    if not v_is_owner then
      select membership.status, membership.scopes
        into v_membership_status, v_scopes
      from public.universe_memberships membership
      where membership.realm_id = v_realm_id
        and membership.user_id = v_user_id;
      if not found or v_membership_status <> 'active' then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
      if v_command_type <> 'membership.accept'
        and not (v_required_scope = any (v_scopes))
      then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
    end if;
    return jsonb_set(v_stored_result, '{idempotent_replay}', 'true'::jsonb, true);
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('universe-stream:' || v_stream_type || ':' || v_stream_id, 0)
  );
  select projection.version, projection.entity, projection.is_public
    into v_current_version, v_current_entity, v_current_public
  from public.universe_entities projection
  where projection.realm_id = v_realm_id
    and projection.entity_type = v_stream_type
    and projection.entity_id = v_stream_id
  for update;
  if not found then
    v_current_version := 0;
    v_current_entity := '{}'::jsonb;
    v_current_public := false;
  end if;
  if v_current_version <> v_expected_version then
    raise exception using
      errcode = 'P0001',
      message = 'universe_version_conflict',
      detail = jsonb_build_object(
        'error', 'MUSE_VERSION_CONFLICT',
        'expected_version', v_expected_version,
        'current_version', v_current_version
      )::text;
  end if;

  if v_command_type = 'realm.create' then
    if v_expected_version <> 0 or exists (
      select 1 from public.universe_realms realm where realm.realm_id = v_realm_id
    ) then
      raise exception using
        errcode = 'P0001',
        message = 'universe_version_conflict',
        detail = jsonb_build_object(
          'error', 'MUSE_VERSION_CONFLICT',
          'expected_version', v_expected_version,
          'current_version', 1
        )::text;
    end if;
    if jsonb_typeof(v_payload -> 'mode') <> 'string'
      or jsonb_typeof(v_payload -> 'name') <> 'string'
      or coalesce(v_payload ->> 'mode', '') not in ('private', 'team', 'network', 'public')
      or char_length(coalesce(v_payload ->> 'name', '')) not between 1 and 200
      or exists (
        select 1
        from jsonb_object_keys(v_payload) as field(key)
        where not (field.key = any (array['id', 'name', 'mode', 'visibility']::text[]))
      )
    then
      raise exception using errcode = 'P0001', message = 'universe_invalid_command';
    end if;
    v_actor_id := 'ply_' || gen_random_uuid()::text;
    v_scopes := array['*']::text[];
    v_is_owner := true;
    v_realm_public := (v_payload ->> 'mode') = 'public';
    v_is_public := v_realm_public;
    v_payload := v_payload || jsonb_build_object('owner_id', v_actor_id);
    insert into public.universe_realms (
      realm_id, owner_user_id, name, mode, is_public, version, metadata,
      created_at, updated_at
    ) values (
      v_realm_id, v_user_id, v_payload ->> 'name', v_payload ->> 'mode',
      v_realm_public, 1, v_payload, v_occurred_at, v_occurred_at
    );
    insert into public.universe_memberships (
      realm_id, user_id, membership_id, player_id, status, scopes, metadata,
      created_at, updated_at
    ) values (
      v_realm_id, v_user_id, 'mbr_' || gen_random_uuid()::text,
      v_actor_id, 'active', v_scopes, '{}'::jsonb,
      v_occurred_at, v_occurred_at
    );
  else
    select realm.owner_user_id = v_user_id, realm.is_public
      into v_is_owner, v_realm_public
    from public.universe_realms realm
    where realm.realm_id = v_realm_id
    for update;
    if not found then
      raise exception using errcode = 'P0001', message = 'universe_not_found';
    end if;

    select membership.membership_id, membership.player_id,
           membership.status, membership.scopes
      into v_membership_id, v_actor_id, v_membership_status, v_scopes
    from public.universe_memberships membership
    where membership.realm_id = v_realm_id and membership.user_id = v_user_id
    for update;
    if not found then
      if v_is_owner then
        v_actor_id := v_user_id::text;
        v_membership_status := 'active';
        v_scopes := array['*']::text[];
      else
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
    end if;
    if v_command_type = 'membership.accept' then
      if v_membership_status <> 'invited' or v_membership_id <> v_stream_id then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
      v_scopes := array_append(v_scopes, 'membership:accept');
    elsif v_membership_status <> 'active' then
      raise exception using errcode = 'P0001', message = 'universe_forbidden';
    end if;
    if not ('*' = any (v_scopes) or v_required_scope = any (v_scopes)) then
      raise exception using errcode = 'P0001', message = 'universe_forbidden';
    end if;

    v_is_public := v_public_capable and coalesce(v_payload ->> 'visibility', '') = 'public';
    if v_is_public and not v_realm_public then
      raise exception using errcode = 'P0001', message = 'universe_forbidden';
    end if;
    if v_is_public and v_current_version > 0 and not v_current_public then
      raise exception using errcode = 'P0001', message = 'universe_forbidden';
    end if;
    v_needs_approval := v_approval_required or v_is_public;
    if v_needs_approval then
      if v_approval_id is null then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
      v_subject_hash := encode(
        digest(convert_to(v_payload::text, 'UTF8'), 'sha256'),
        'hex'
      );
      perform 1
      from public.universe_approval_grants approval
      where approval.approval_id = v_approval_id
        and approval.realm_id = v_realm_id
        and approval.actor_user_id = v_user_id
        and approval.action = v_command_type
        and approval.correlation_id = v_correlation_id
        and approval.subject_hash = v_subject_hash
        and approval.state = 'approved'
        and approval.expires_at > v_occurred_at
      for update;
      if not found then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
      update public.universe_approval_grants
      set state = 'consumed', consumed_at = v_occurred_at
      where approval_id = v_approval_id;
    end if;

    if v_command_type = 'membership.invite' then
      if not (v_payload ? 'user_id')
        or jsonb_typeof(v_payload -> 'user_id') <> 'string'
        or jsonb_typeof(v_payload -> 'player_id') <> 'string'
      then
        raise exception using errcode = 'P0001', message = 'universe_invalid_command';
      end if;
      begin
        v_target_user_id := (v_payload ->> 'user_id')::uuid;
      exception when invalid_text_representation then
        raise exception using errcode = 'P0001', message = 'universe_invalid_command';
      end;
      v_target_player_id := v_payload ->> 'player_id';
      if v_target_player_id is null
        or v_target_player_id !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
        or jsonb_typeof(coalesce(v_payload -> 'scopes', '[]'::jsonb)) <> 'array'
        or exists (
          select 1
          from jsonb_array_elements(coalesce(v_payload -> 'scopes', '[]'::jsonb)) as item(value)
          where jsonb_typeof(item.value) <> 'string'
        )
      then
        raise exception using errcode = 'P0001', message = 'universe_invalid_command';
      end if;
      select coalesce(
        array_agg(item.value #>> '{}' order by item.value #>> '{}'),
        array[]::text[]
      )
        into v_target_scopes
      from jsonb_array_elements(coalesce(v_payload -> 'scopes', '[]'::jsonb)) as item(value);
      if '*' = any (v_target_scopes)
        or exists (
          select 1
          from unnest(v_target_scopes) as granted_scope(value)
          where granted_scope.value !~ '^[a-z][a-z0-9_.-]*:[a-z][a-z0-9_.-]*$'
        )
        or (not v_is_owner and not (v_target_scopes <@ v_scopes))
      then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
      insert into public.universe_memberships (
        realm_id, user_id, membership_id, player_id, status, scopes, metadata,
        created_at, updated_at
      ) values (
        v_realm_id, v_target_user_id, v_stream_id, v_target_player_id,
        'invited', v_target_scopes, '{}'::jsonb, v_occurred_at, v_occurred_at
      )
      on conflict (realm_id, user_id) do update
      set membership_id = excluded.membership_id,
          player_id = excluded.player_id,
          status = 'invited',
          scopes = excluded.scopes,
          metadata = excluded.metadata,
          updated_at = excluded.updated_at
      where public.universe_memberships.status = 'removed';
      get diagnostics v_rows = row_count;
      if v_rows <> 1 then
        raise exception using errcode = 'P0001', message = 'universe_invalid_command';
      end if;
      v_payload := v_payload || jsonb_build_object('status', 'invited');
    elsif v_command_type = 'membership.accept' then
      update public.universe_memberships
      set status = 'active', updated_at = v_occurred_at
      where realm_id = v_realm_id
        and user_id = v_user_id
        and membership_id = v_stream_id
        and status = 'invited';
      get diagnostics v_rows = row_count;
      if v_rows <> 1 then
        raise exception using errcode = 'P0001', message = 'universe_forbidden';
      end if;
      v_payload := v_payload || jsonb_build_object('status', 'active');
    end if;

    update public.universe_realms
    set version = version + 1, updated_at = v_occurred_at
    where realm_id = v_realm_id;
  end if;

  v_sequence := nextval(pg_get_serial_sequence('public.universe_events', 'sequence'));
  v_authorization := jsonb_build_object(
    'allowed', true,
    'reason', case when v_is_owner then 'authenticated realm owner' else 'active realm membership' end,
    'scopes', to_jsonb(v_scopes),
    'owner_gate', case when v_needs_approval then 'consumed' else 'not_required' end
  );
  v_provenance := jsonb_build_object(
    'source', 'supabase_authenticated_user',
    'evidence', jsonb_build_array('auth:verified'),
    'confidence', 1.0,
    'signature', null
  );
  v_entity := coalesce(v_current_entity, '{}'::jsonb)
    || v_payload
    || jsonb_build_object(
      'id', v_stream_id,
      'entity_type', v_stream_type,
      'realm_id', v_realm_id,
      'version', v_current_version + 1,
      'updated_at', v_occurred_at,
      'simulation', v_simulation
    );
  v_event := jsonb_build_object(
    'sequence', v_sequence,
    'event_id', v_event_id,
    'schema_version', 1,
    'event_type', v_event_type,
    'realm_id', v_realm_id,
    'actor_id', v_actor_id,
    'stream_type', v_stream_type,
    'stream_id', v_stream_id,
    'stream_version', v_current_version + 1,
    'authorization', case when v_is_public then jsonb_build_object(
      'allowed', true,
      'reason', 'authorized public submission',
      'scopes', '[]'::jsonb,
      'owner_gate', v_authorization -> 'owner_gate'
    ) else v_authorization end,
    'causation_id', v_causation_id,
    'correlation_id', v_correlation_id,
    'occurred_at', v_occurred_at,
    'payload', v_payload,
    'provenance', v_provenance,
    'simulation', v_simulation,
    'rollback', case when v_is_public then '{}'::jsonb
      else coalesce(v_current_entity, '{}'::jsonb) end
  );

  insert into public.universe_events (
    sequence, event_id, schema_version, event_type, realm_id,
    actor_user_id, actor_id, stream_type, stream_id, stream_version,
    authorization, causation_id, correlation_id, occurred_at, payload,
    provenance, simulation, rollback, is_public, event
  ) values (
    v_sequence, v_event_id, 1, v_event_type, v_realm_id,
    v_user_id, v_actor_id, v_stream_type, v_stream_id, v_current_version + 1,
    v_authorization, v_causation_id, v_correlation_id, v_occurred_at, v_payload,
    v_provenance, v_simulation, coalesce(v_current_entity, '{}'::jsonb),
    v_is_public, v_event
  );

  insert into public.universe_entities (
    realm_id, entity_type, entity_id, version, is_public, deleted,
    updated_at, entity
  ) values (
    v_realm_id, v_stream_type, v_stream_id, v_current_version + 1,
    v_is_public,
    case when v_payload ? 'deleted' then (v_payload ->> 'deleted')::boolean else false end,
    v_occurred_at, v_entity
  )
  on conflict (realm_id, entity_type, entity_id) do update
  set version = excluded.version,
      is_public = excluded.is_public,
      deleted = excluded.deleted,
      updated_at = excluded.updated_at,
      entity = excluded.entity
  where public.universe_entities.version = v_current_version;
  get diagnostics v_rows = row_count;
  if v_rows <> 1 then
    raise exception using
      errcode = 'P0001',
      message = 'universe_version_conflict',
      detail = jsonb_build_object(
        'error', 'MUSE_VERSION_CONFLICT',
        'expected_version', v_expected_version,
        'current_version', v_current_version
      )::text;
  end if;

  v_result := jsonb_build_object(
    'event', v_event,
    'entity', v_entity,
    'idempotent_replay', false
  );
  insert into public.universe_command_results (
    realm_id, command_id, actor_user_id, command_fingerprint,
    event_id, result, created_at
  ) values (
    v_realm_id, v_command_id, v_user_id, v_command_fingerprint,
    v_event_id, v_result, v_occurred_at
  );
  return v_result;
end;
$$;

revoke all on function public.execute_universe_command(jsonb) from public;
revoke execute on function public.execute_universe_command(jsonb) from anon;
grant execute on function public.execute_universe_command(jsonb) to authenticated;
