"""Free/local benchmark scorecard producer — a reproducible proof-bar artifact.

This module emits a deterministic, **fully-offline** benchmark scorecard for the
10/10 program: a free (no paid model, no network) proof artifact that can be
regenerated byte-for-byte and checked into a PR or CI log.

It does **not** invent a parallel scoring system. It *reuses* the repo's existing
machinery end-to-end:

* :mod:`hermes_cli.jarvis_prime.research_fabric.benchmarks`
  (:class:`BenchmarkTaskSpec`, :func:`run_suite`, :class:`SuiteResult`) grades a
  suite of *verifiable* tasks through the executable algorithms verifier — each
  task embeds a candidate solution whose correct output is known exactly and is
  scored offline by running it in the research-fabric sandbox (``python -I -S``
  subprocess, scrubbed env, dead-proxy network). No model is ever called.
* :class:`hermes_cli.jarvis_prime.model_scorecard.ModelScorecard` is the
  structured scorecard shape the rest of muse consumes; each graded task becomes
  one card (``tests_passed`` / ``tests_failed`` from the verifier's correctness),
  so the artifact is ``ModelScorecard``-compatible rather than a new format.
* :class:`hermes_cli.jarvis_prime.task_router.TaskClass` supplies the lane labels
  the per-class pass-rate is bucketed by, matching the router's vocabulary.

Determinism contract: the artifact contains **no** wall-clock latency, no
timestamps, and no host-specific paths — only correctness-derived fields and the
fixed built-in suite — so two runs on the same code produce identical bytes. The
built-in tasks are pure, total functions over small fixed inputs (no randomness;
any randomness elsewhere would be seeded). :func:`produce_scorecard` **never
raises**: on any internal failure it degrades to an honest all-zero scorecard
with the failure recorded in ``notes``.

Stdlib-light: only the standard library plus the in-repo reuse above.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Optional

from hermes_cli.jarvis_prime.model_scorecard import ModelScorecard

# A stable, model-agnostic label for the synthetic "model under test". The proof
# bar measures the *verifier*, not a model — these tasks ship their own correct
# candidate — so the label is a constant, never a real provider/model id.
VERIFIER_MODEL = "verifiable-suite"
VERIFIER_PROVIDER = "offline"

# Schema version for the emitted artifact. Bump only on a breaking shape change.
SCORECARD_SCHEMA_VERSION = 1


@dataclass(frozen=True)
class VerifiableTask:
    """One built-in, deterministically-checkable task.

    ``candidate`` is correct-by-construction Python defining ``entrypoint``; the
    verifier runs it against ``cases`` (each ``(args, expected)``) offline. The
    ``task_class`` is a :class:`TaskClass` *value* used purely as a reporting
    bucket (this is a free proof bar, not a routing decision).
    """

    task_id: str
    task_class: str
    entrypoint: str
    candidate: str
    cases: tuple[tuple[list[Any], Any], ...]


# The built-in proof suite: a handful of pure string/number transforms whose
# correct output is known exactly. Public + held-out cases are the same fixed
# set (this grades a *known-correct* candidate, not an unknown solver), so the
# correctness signal is fully determined. Two reporting lanes are exercised so
# the per-class breakdown is non-trivial.
BUILTIN_TASKS: tuple[VerifiableTask, ...] = (
    VerifiableTask(
        task_id="reverse_string",
        task_class="coding_build",
        entrypoint="solve",
        candidate="def solve(s):\n    return s[::-1]\n",
        cases=(
            (["hermes"], "semreh"),
            ([""], ""),
            (["a"], "a"),
            (["ab cd"], "dc ba"),
        ),
    ),
    VerifiableTask(
        task_id="sum_list",
        task_class="coding_build",
        entrypoint="solve",
        candidate="def solve(xs):\n    return sum(xs)\n",
        cases=(
            ([[1, 2, 3]], 6),
            ([[]], 0),
            ([[10, -5, 5]], 10),
            ([[-1, -2, -3]], -6),
        ),
    ),
    VerifiableTask(
        task_id="upper_case",
        task_class="summarization",
        entrypoint="solve",
        candidate="def solve(s):\n    return s.upper()\n",
        cases=(
            (["hermes"], "HERMES"),
            (["MixedCase"], "MIXEDCASE"),
            ([""], ""),
        ),
    ),
    VerifiableTask(
        task_id="count_vowels",
        task_class="summarization",
        entrypoint="solve",
        candidate=(
            "def solve(s):\n"
            "    return sum(1 for c in s.lower() if c in 'aeiou')\n"
        ),
        cases=(
            (["hermes"], 2),
            (["sky"], 0),
            (["AEIOU"], 5),
            ([""], 0),
        ),
    ),
    VerifiableTask(
        task_id="slugify",
        task_class="coding_build",
        entrypoint="solve",
        candidate=(
            "import re\n"
            "def solve(s):\n"
            "    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')\n"
        ),
        cases=(
            (["Hello, World!"], "hello-world"),
            (["  Hermes  Agent  "], "hermes-agent"),
            (["already-slug"], "already-slug"),
        ),
    ),
)


@dataclass
class ClassScore:
    """Per-:class:`TaskClass` aggregate for the emitted artifact."""

    task_class: str
    tasks: int
    tasks_passed: int
    pass_rate: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_class": self.task_class,
            "tasks": self.tasks,
            "tasks_passed": self.tasks_passed,
            "pass_rate": round(self.pass_rate, 4),
        }


@dataclass
class DepthScorecard:
    """A deterministic, offline benchmark scorecard (proof-bar artifact).

    ``cards`` holds one :class:`ModelScorecard`-shaped dict per graded task, so
    the artifact composes with everything that already consumes scorecards. The
    aggregate fields are derived from the verifier's correctness only — no
    latency, no timestamps — so the whole artifact is reproducible byte-for-byte.
    """

    schema_version: int
    model: str
    provider: str
    overall_score: float
    tasks_total: int
    tasks_passed: int
    per_class: list[ClassScore] = field(default_factory=list)
    cards: list[dict[str, Any]] = field(default_factory=list)
    offline: bool = True
    deterministic: bool = True
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "model": self.model,
            "provider": self.provider,
            "overall_score": round(self.overall_score, 4),
            "tasks_total": self.tasks_total,
            "tasks_passed": self.tasks_passed,
            "per_class": [c.to_dict() for c in self.per_class],
            "cards": list(self.cards),
            "offline": self.offline,
            "deterministic": self.deterministic,
            "notes": list(self.notes),
        }

    def to_json(self) -> str:
        """Canonical JSON (sorted keys) — stable bytes for diffing/CI."""

        return json.dumps(self.to_dict(), sort_keys=True, indent=2)


def _empty_scorecard(note: str) -> DepthScorecard:
    """An honest all-zero scorecard used when grading cannot proceed."""

    return DepthScorecard(
        schema_version=SCORECARD_SCHEMA_VERSION,
        model=VERIFIER_MODEL,
        provider=VERIFIER_PROVIDER,
        overall_score=0.0,
        tasks_total=0,
        tasks_passed=0,
        per_class=[],
        cards=[],
        notes=[note],
    )


def _spec_payload(task: VerifiableTask) -> dict[str, Any]:
    """Build the research-fabric spec payload for one verifiable task.

    Public and held-out cases are identical (the candidate is known-correct), so
    the algorithm verifier's binary per-case grading is fully determined.
    """

    cases = [{"args": list(args), "expected": expected} for args, expected in task.cases]
    return {
        "entrypoint": task.entrypoint,
        "prompt": task.task_id,
        "public_cases": cases,
        "holdout_cases": cases,
        "candidate": task.candidate,
    }


def _card_for(task: VerifiableTask, *, correctness: float, ran: bool) -> ModelScorecard:
    """Map one verifier outcome onto a :class:`ModelScorecard`.

    A fully-correct, executed task is one passing test; anything else is a
    failing test. We deliberately record only outcome counts (no latency/cost),
    keeping the card — and therefore the artifact — deterministic.
    """

    passed = 1 if (ran and correctness >= 1.0) else 0
    failed = 0 if passed else 1
    return ModelScorecard(
        model=VERIFIER_MODEL,
        provider=VERIFIER_PROVIDER,
        task_type=task.task_class,
        tests_passed=passed,
        tests_failed=failed,
        # Pin created_at so the card dict is reproducible across runs; this is a
        # synthetic proof artifact, not a live measurement, so a constant epoch
        # marker is the honest, deterministic choice.
        created_at="1970-01-01T00:00:00+00:00",
    )


def produce_scorecard(
    tasks: Optional[tuple[VerifiableTask, ...]] = None,
) -> DepthScorecard:
    """Produce a deterministic, fully-offline benchmark scorecard.

    Grades the built-in (or supplied) verifiable tasks through the existing
    research-fabric benchmark harness and aggregates per-:class:`TaskClass`
    pass-rate plus an overall verifiable score. The result is a
    :class:`ModelScorecard`-compatible artifact (one card per task).

    Guarantees: 100% offline (no model call, no network in this process), and
    deterministic (identical inputs → identical ``to_dict()``/``to_json()``).
    Never raises — on any internal error it returns an honest empty scorecard
    with the reason in ``notes``.
    """

    suite = tasks if tasks is not None else BUILTIN_TASKS
    try:
        # Imported lazily so a degraded/stripped install still imports this
        # module and gets an honest empty scorecard rather than an ImportError.
        from hermes_cli.jarvis_prime.research_fabric.benchmarks import (
            BenchmarkTaskSpec,
            run_suite,
        )
    except Exception as exc:  # pragma: no cover - exercised only on broken install
        return _empty_scorecard(f"benchmark harness unavailable: {exc!r}")

    if not suite:
        return _empty_scorecard("no verifiable tasks to grade")

    try:
        specs = [
            BenchmarkTaskSpec(
                task_id=t.task_id,
                domain=t.task_class,
                kind="algorithm",
                payload=_spec_payload(t),
            )
            for t in suite
        ]
        result = run_suite(specs)
    except Exception as exc:  # never raise to the caller
        return _empty_scorecard(f"grading failed: {exc!r}")

    # Index outcomes by task_id; run_suite preserves order, but index defensively.
    outcomes = {o.task_id: o for o in result.outcomes}

    cards: list[ModelScorecard] = []
    by_class: dict[str, list[int]] = {}
    notes: list[str] = []
    for t in suite:
        o = outcomes.get(t.task_id)
        if o is None:  # pragma: no cover - run_suite always emits one per spec
            correctness, ran = 0.0, False
            notes.append(f"missing outcome for {t.task_id}")
        else:
            correctness, ran = o.correctness, o.ran
        card = _card_for(t, correctness=correctness, ran=ran)
        cards.append(card)
        by_class.setdefault(t.task_class, []).append(card.tests_passed)

    tasks_total = len(cards)
    tasks_passed = sum(c.tests_passed for c in cards)
    overall = (tasks_passed / tasks_total) if tasks_total else 0.0

    per_class = [
        ClassScore(
            task_class=name,
            tasks=len(passes),
            tasks_passed=sum(passes),
            pass_rate=(sum(passes) / len(passes)) if passes else 0.0,
        )
        # Sorted for stable, deterministic ordering in the artifact.
        for name, passes in sorted(by_class.items())
    ]

    return DepthScorecard(
        schema_version=SCORECARD_SCHEMA_VERSION,
        model=VERIFIER_MODEL,
        provider=VERIFIER_PROVIDER,
        overall_score=overall,
        tasks_total=tasks_total,
        tasks_passed=tasks_passed,
        per_class=per_class,
        cards=[c.to_dict() for c in cards],
        notes=notes,
    )


def render_scorecard(scorecard: Optional[DepthScorecard] = None) -> str:
    """Human-readable one-screen summary of the scorecard."""

    sc = scorecard if scorecard is not None else produce_scorecard()
    lines = [
        "FREE/LOCAL BENCHMARK SCORECARD (offline, deterministic)",
        f"  model={sc.model} [{sc.provider}]  schema_v{sc.schema_version}",
        f"  overall: {sc.tasks_passed}/{sc.tasks_total} "
        f"verifiable tasks passed (score={sc.overall_score:.2f})",
    ]
    for c in sc.per_class:
        lines.append(
            f"    {c.task_class:<16} {c.tasks_passed}/{c.tasks} "
            f"(pass_rate={c.pass_rate:.2f})"
        )
    for note in sc.notes:
        lines.append(f"  note: {note}")
    return "\n".join(lines)


__all__ = [
    "VERIFIER_MODEL",
    "VERIFIER_PROVIDER",
    "SCORECARD_SCHEMA_VERSION",
    "VerifiableTask",
    "ClassScore",
    "DepthScorecard",
    "BUILTIN_TASKS",
    "produce_scorecard",
    "render_scorecard",
]
